from __future__ import annotations

from fractions import Fraction
from tokenize import Exponent
from typing import TYPE_CHECKING, Any, ClassVar, Generic, Literal, Never, TypeAlias, TypeVar, overload

import numpy as np
from numpy._typing import NDArray
import numpy.typing as npt

Number: TypeAlias = float | int | np.floating[Any]
TensorData: TypeAlias = npt.NDArray[np.floating[Any]]


class DimCoords:
    length: Fraction
    time: Fraction
    mass: Fraction
    dimensionless: bool

    def __init__(self, 
        length: Fraction | int = 0, 
        time: Fraction | int = 0, 
        mass: Fraction | int = 0
    ) -> None: ...

    def __mul__(self, o: DimCoords) -> DimCoords: ...
    def __truediv__(self, o: DimCoords) -> DimCoords: ...
    def __pow__(self, p: Fraction | int | float) -> DimCoords: ...
    def to_dimension(self) -> type[Dim]: ...


class Dim:
    _d: ClassVar[DimCoords]


class D:
    class Dimless(Dim): ...
    class Angle(Dim): ...
    class AngularVelocity(Dim): ...
    class AngularAcc(Dim): ...
    class AngularJerk(Dim): ...
    class Length(Dim): ...
    class InvLength(Dim): ...
    class Time(Dim): ...
    class Mass(Dim): ...
    class Velocity(Dim): ...
    class Acceleration(Dim): ...
    class Force(Dim): ...
    class GrativationnalParam(Dim): ...

ExponentNumerator = TypeVar("ExponentNumerator", bound=int)
ExponentDenominator = TypeVar("ExponentDenominator", bound=int)
SomeDim = TypeVar("SomeDim", bound=Dim)
SomeOtherDim = TypeVar("SomeOtherDim", bound=Dim)

class ProductDim(Dim, Generic[SomeDim, SomeOtherDim]): ...
class QuotientDim(Dim, Generic[SomeDim, SomeOtherDim]): ...
class PowerDim(Dim, Generic[SomeDim, ExponentNumerator, ExponentDenominator]): ...

N3: TypeAlias = Literal[-3]
N2: TypeAlias = Literal[-2]
N1: TypeAlias = Literal[-1]
OO: TypeAlias = Literal[0]
P1: TypeAlias = Literal[1]
P2: TypeAlias = Literal[2]
P3: TypeAlias = Literal[3]


class Tensor(Generic[SomeDim]):
    _values: TensorData
    _base_tensor_class: ClassVar[type[Tensor[Any]]]

    @property
    def dim_coords(self) -> DimCoords: ...

    @property
    def dim(self) -> type[SomeDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor[SomeOtherDim]: ...
    def copy(self) -> Tensor[SomeDim]: ...
    def ensure_compatible_dimensions(self, o: Tensor[Any]) -> bool: ...
    def check(self, dim: type[Dim]) -> bool: ...
    def get_raw_array(self, units: str = "1") -> npt.NDArray[np.float64]: ...

    def __pos__(self) -> Tensor[SomeDim]: ...

    def __neg__(self) -> Tensor[SomeDim]: ...


class Tensor_S(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> Number | npt.NDArray[np.float64]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...
    def copy(self) -> Tensor_S[SomeDim]: ...

    def magnitude(self, units: str = "1") -> np.float64 | npt.NDArray[np.float64]: ...

    def __pos__(self) -> Tensor_S[SomeDim]: ...

    def __neg__(self) -> Tensor_S[SomeDim]: ...

    @overload
    def __add__(self: Tensor_S[D.Dimless], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __add__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    @overload
    def __add__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...

    @overload
    def __sub__(self: Tensor_S[D.Dimless], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __sub__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    @overload
    def __sub__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...

    @overload
    def __mul__(self: Tensor_S[D.Dimless], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __mul__(self: Tensor_S[D.Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...

    @overload
    def __mul__(self: Tensor_S[SomeDim], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[SomeDim]: ...

    @overload
    def __mul__(self: Tensor_S[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_S[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Tensor_S[D.Dimless], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __truediv__(self: Tensor_S[D.Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_S[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Tensor_S[SomeDim], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[SomeDim]: ...

    @overload
    def __truediv__(self: Tensor_S[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_S[QuotientDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __mod__(self: Tensor_S[D.Dimless], o: Number | Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __mod__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    @overload
    def __mod__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...

    @overload
    def __radd__(self: Tensor_S[D.Dimless], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __radd__(self: Tensor_S[PowerDim[D.Dimless, ExponentNumerator, ExponentDenominator]], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __radd__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rsub__(self: Tensor_S[D.Dimless], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rsub__(self: Tensor_S[PowerDim[D.Dimless, ExponentNumerator, ExponentDenominator]], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rsub__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rmul__(self: Tensor_S[D.Dimless], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rmul__(self: Tensor_S[PowerDim[D.Dimless, ExponentNumerator, ExponentDenominator]], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rmul__(self: Tensor_S[SomeDim], o: Number) -> Tensor_S[SomeDim]: ...

    def __rmul__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_S[D.Dimless], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Tensor_S[PowerDim[D.Dimless, ExponentNumerator, ExponentDenominator]], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Tensor_S[SomeDim], o: Number) -> Tensor_S[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rmod__(self: Tensor_S[D.Dimless], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rmod__(self: Tensor_S[PowerDim[D.Dimless, ExponentNumerator, ExponentDenominator]], o: Number) -> Tensor_S[D.Dimless]: ...

    @overload
    def __rmod__(self: Tensor_S[SomeDim], o: Number) -> Never: ...

    def __rmod__(self, o: object) -> Tensor_S[Any]: ...

    def __lt__(self, o: object) -> bool: ...

    def __le__(self, o: object) -> bool: ...

    def __gt__(self, o: object) -> bool: ...

    def __ge__(self, o: object) -> bool: ...

class Tensor_V3(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_components(
        cls,
        x: Tensor_S[SomeDim] | Number,
        y: Tensor_S[SomeDim] | Number,
        z: Tensor_S[SomeDim] | Number,
    ) -> Tensor_V3[SomeDim]: ...

    @staticmethod
    def from_spherical(
        theta: Tensor_S[D.Angle],
        delta: Tensor_S[D.Angle],
        rho: Tensor_S[SomeOtherDim],
    ) -> Tensor_V3[SomeOtherDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    def copy(self) -> Tensor_V3[SomeDim]: ...

    @overload
    def dot(self: Tensor_V3[D.Dimless], o: Tensor_V3[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def dot(self: Tensor_V3[D.Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...

    @overload
    def dot(self: Tensor_V3[SomeDim], o: Tensor_V3[D.Dimless]) -> Tensor_S[SomeDim]: ...

    def dot(self, o: Tensor_V3[SomeOtherDim]) -> Tensor_S[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Tensor_V3[D.Dimless], o: Tensor_V3[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def cross(self: Tensor_V3[D.Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...

    @overload
    def cross(self: Tensor_V3[SomeDim], o: Tensor_V3[D.Dimless]) -> Tensor_V3[SomeDim]: ...

    def cross(self, o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...

    # --- arithmetic / tensor operators involving Tensor_V3 and Tensor_S ---
    @overload
    def __add__(self: Tensor_V3[D.Dimless], o: Number | Tensor_V3[D.Dimless] | Tensor_S[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __add__(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeDim] | Tensor_S[SomeDim]) -> Tensor_V3[SomeDim]: ...

    def __add__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __radd__(self: Tensor_V3[D.Dimless], o: Number) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __radd__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __sub__(self: Tensor_V3[D.Dimless], o: Number | Tensor_V3[D.Dimless] | Tensor_S[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __sub__(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeDim] | Tensor_S[SomeDim]) -> Tensor_V3[SomeDim]: ...

    def __sub__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rsub__(self: Tensor_V3[D.Dimless], o: Number) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __rsub__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __mul__(self: Tensor_V3[D.Dimless], o: Number | Tensor_S[D.Dimless] | Tensor_V3[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __mul__(self: Tensor_V3[D.Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...

    @overload
    def __mul__(self: Tensor_V3[SomeDim], o: Number | Tensor_S[D.Dimless] | Tensor_V3[D.Dimless]) -> Tensor_V3[SomeDim]: ...

    @overload
    def __mul__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...

    def __mul__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rmul__(self: Tensor_V3[D.Dimless], o: Number) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __rmul__(self: Tensor_V3[SomeDim], o: Number) -> Tensor_V3[SomeDim]: ...

    def __rmul__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __truediv__(self: Tensor_V3[D.Dimless], o: Number | Tensor_S[D.Dimless] | Tensor_V3[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __truediv__(self: Tensor_V3[D.Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Tensor_V3[SomeDim], o: Number | Tensor_S[D.Dimless] | Tensor_V3[D.Dimless]) -> Tensor_V3[SomeDim]: ...

    @overload
    def __truediv__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[QuotientDim[SomeDim, SomeOtherDim]]: ...

    def __truediv__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_V3[D.Dimless], o: Number) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Tensor_V3[SomeDim], o: Number) -> Tensor_V3[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __mod__(self: Tensor_V3[D.Dimless], o: Number | Tensor_S[D.Dimless] | Tensor_V3[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __mod__(self: Tensor_V3[D.Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Never: ...

    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...

    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeDim] | Tensor_V3[SomeDim]) -> Tensor_V3[SomeDim]: ...

    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Never: ...

    def __mod__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rmod__(self: Tensor_V3[D.Dimless], o: Number) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __rmod__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...

    def __rmod__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __matmul__(self: Tensor_V3[D.Dimless], o: Tensor_V3[D.Dimless]) -> Tensor_S[D.Dimless]: ...

    @overload
    def __matmul__(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeOtherDim]) -> Tensor_S[ProductDim[SomeDim, SomeOtherDim]]: ...

    def __matmul__(self, o: object) -> Tensor_S[Any]: ...

    @property
    def size(self) -> int: ...

    @property
    def x(self) -> Tensor_S[SomeDim]: ...

    @property
    def y(self) -> Tensor_S[SomeDim]: ...

    @property
    def z(self) -> Tensor_S[SomeDim]: ...

    @property
    def length(self) -> Tensor_S[SomeDim]: ...

    @property
    def length_squared(self) -> Tensor_S[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> Tensor_S[D.Angle]: ...

    @property
    def delta(self) -> Tensor_S[D.Angle]: ...

    def angle(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeDim]) -> Tensor_S[D.Angle]: ...
    def normalized(self) -> Tensor_V3[D.Dimless]: ...

    def __pos__(self) -> Tensor_V3[SomeDim]: ...

    def __neg__(self) -> Tensor_V3[SomeDim]: ...


class Tensor_M33(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_elements(
        cls,
        a: Tensor_S[SomeDim] | Number,
        b: Tensor_S[SomeDim] | Number,
        c: Tensor_S[SomeDim] | Number,
        d: Tensor_S[SomeDim] | Number,
        e: Tensor_S[SomeDim] | Number,
        f: Tensor_S[SomeDim] | Number,
        g: Tensor_S[SomeDim] | Number,
        h: Tensor_S[SomeDim] | Number,
        i: Tensor_S[SomeDim] | Number,
    ) -> Tensor_M33[SomeDim]: ...

    @property
    def det(self) -> Number: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_M33[SomeOtherDim]: ...
    def copy(self) -> Tensor_M33[SomeDim]: ...

    def __pos__(self) -> Tensor_M33[SomeDim]: ...

    def __neg__(self) -> Tensor_M33[SomeDim]: ...

    @overload
    def __radd__(self: Tensor_M33[D.Dimless], o: Number) -> Tensor_M33[D.Dimless]: ...

    @overload
    def __radd__(self: Tensor_M33[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rsub__(self: Tensor_M33[D.Dimless], o: Number) -> Tensor_M33[D.Dimless]: ...

    @overload
    def __rsub__(self: Tensor_M33[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rmul__(self: Tensor_M33[D.Dimless], o: Number) -> Tensor_M33[D.Dimless]: ...

    @overload
    def __rmul__(self: Tensor_M33[SomeDim], o: Number) -> Tensor_M33[SomeDim]: ...

    def __rmul__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_M33[D.Dimless], o: Number) -> Tensor_M33[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Tensor_M33[SomeDim], o: Number) -> Tensor_M33[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def inverse(self: Tensor_M33[D.Dimless]) -> Tensor_M33[D.Dimless]: ...

    @overload
    def inverse(self: Tensor_M33[SomeDim]) -> Tensor_M33[QuotientDim[D.Dimless, SomeDim]]: ...


class Scalar(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, value: Number) -> None: ...

    def magnitude(self, units: str = ...) -> Number: ...
    def cast(self, dim: type[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...
    def copy(self) -> Scalar[SomeDim]: ...

    @property
    def base_unit_value(self) -> Number: ...

    def __pos__(self) -> Scalar[SomeDim]: ...

    def __neg__(self) -> Scalar[SomeDim]: ...

    @overload
    def __radd__(self: Scalar[D.Dimless], o: Number) -> Scalar[D.Dimless]: ...

    @overload
    def __radd__(self: Scalar[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rsub__(self: Scalar[D.Dimless], o: Number) -> Scalar[D.Dimless]: ...

    @overload
    def __rsub__(self: Scalar[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rmul__(self: Scalar[D.Dimless], o: Number) -> Scalar[D.Dimless]: ...

    @overload
    def __rmul__(self: Scalar[SomeDim], o: Number) -> Scalar[SomeDim]: ...

    def __rmul__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rtruediv__(self: Scalar[D.Dimless], o: Number) -> Scalar[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Scalar[SomeDim], o: Number) -> Scalar[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rmod__(self: Scalar[D.Dimless], o: Number) -> Scalar[D.Dimless]: ...

    @overload
    def __rmod__(self: Scalar[SomeDim], o: Number) -> Never: ...

    def __rmod__(self, o: object) -> Scalar[Any]: ...

    def __lt__(self, o: object) -> bool: ...

    def __le__(self, o: object) -> bool: ...

    def __gt__(self, o: object) -> bool: ...

    def __ge__(self, o: object) -> bool: ...

    @overload
    def __add__(self: Scalar[D.Dimless], o: Number | Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def __add__(self: Scalar[SomeDim], o: Number) -> Never: ...

    @overload
    def __add__(self: Scalar[SomeDim], o: Scalar[SomeDim]) -> Scalar[SomeDim]: ...

    @overload
    def __add__(self: Scalar[SomeDim], o: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...

    @overload
    def __sub__(self: Scalar[D.Dimless], o: Number | Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def __sub__(self: Scalar[SomeDim], o: Number) -> Never: ...

    @overload
    def __sub__(self: Scalar[SomeDim], o: Scalar[SomeDim]) -> Scalar[SomeDim]: ...

    @overload
    def __sub__(self: Scalar[SomeDim], o: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...

    @overload
    def __mul__(self: Scalar[D.Dimless], o: Number | Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def __mul__(self: Scalar[D.Dimless], o: Scalar[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...

    @overload
    def __mul__(self: Scalar[SomeDim], o: Number | Scalar[D.Dimless]) -> Scalar[SomeDim]: ...

    @overload
    def __mul__(self: Scalar[SomeDim], o: Scalar[SomeOtherDim]) -> Scalar[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Scalar[D.Dimless], o: Number | Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def __truediv__(self: Scalar[D.Dimless], o: Scalar[SomeOtherDim]) -> Scalar[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Scalar[SomeDim], o: Number | Scalar[D.Dimless]) -> Scalar[SomeDim]: ...

    @overload
    def __truediv__(self: Scalar[SomeDim], o: Scalar[SomeOtherDim]) -> Scalar[QuotientDim[SomeDim, SomeOtherDim]]: ...


class ScalarArray(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, values: npt.NDArray[np.floating[Any]]) -> None: ...

    def magnitude(self, units: str = ...) -> np.ndarray: ...
    def cast(self, dim: type[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...
    def copy(self) -> ScalarArray[SomeDim]: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> npt.NDArray[np.float64]: ...

    def __pos__(self) -> ScalarArray[SomeDim]: ...

    def __neg__(self) -> ScalarArray[SomeDim]: ...

    @overload
    def __radd__(self: ScalarArray[D.Dimless], o: Number) -> ScalarArray[D.Dimless]: ...

    @overload
    def __radd__(self: ScalarArray[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rsub__(self: ScalarArray[D.Dimless], o: Number) -> ScalarArray[D.Dimless]: ...

    @overload
    def __rsub__(self: ScalarArray[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rmul__(self: ScalarArray[D.Dimless], o: Number) -> ScalarArray[D.Dimless]: ...

    @overload
    def __rmul__(self: ScalarArray[SomeDim], o: Number) -> ScalarArray[SomeDim]: ...

    def __rmul__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rtruediv__(self: ScalarArray[D.Dimless], o: Number) -> ScalarArray[D.Dimless]: ...

    @overload
    def __rtruediv__(self: ScalarArray[SomeDim], o: Number) -> ScalarArray[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rmod__(self: ScalarArray[D.Dimless], o: Number) -> ScalarArray[D.Dimless]: ...

    @overload
    def __rmod__(self: ScalarArray[SomeDim], o: Number) -> Never: ...

    def __rmod__(self, o: object) -> ScalarArray[Any]: ...

    def __getitem__(self: ScalarArray[SomeDim], index: int) -> Scalar[SomeDim]: ...

    @overload
    def __add__(self: ScalarArray[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def __add__(self: ScalarArray[SomeDim], o: Number) -> Never: ...

    @overload
    def __add__(self: ScalarArray[SomeDim], o: Scalar[SomeDim] | ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...

    @overload
    def __sub__(self: ScalarArray[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def __sub__(self: ScalarArray[SomeDim], o: Number) -> Never: ...

    @overload
    def __sub__(self: ScalarArray[SomeDim], o: Scalar[SomeDim] | ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...

    @overload
    def __mul__(self: ScalarArray[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def __mul__(self: ScalarArray[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...

    @overload
    def __mul__(self: ScalarArray[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[SomeDim]: ...

    @overload
    def __mul__(self: ScalarArray[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: ScalarArray[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def __truediv__(self: ScalarArray[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: ScalarArray[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> ScalarArray[SomeDim]: ...

    @overload
    def __truediv__(self: ScalarArray[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[QuotientDim[SomeDim, SomeOtherDim]]: ...


class Vector3(Tensor_V3[SomeDim], Generic[SomeDim]):
    O: ClassVar[Vector3[D.Dimless]]
    X: ClassVar[Vector3[D.Dimless]]
    Y: ClassVar[Vector3[D.Dimless]]
    Z: ClassVar[Vector3[D.Dimless]]

    @property
    def x(self) -> Scalar[SomeDim]: ...

    @property
    def y(self) -> Scalar[SomeDim]: ...

    @property
    def z(self) -> Scalar[SomeDim]: ...

    @property
    def length(self) -> Scalar[SomeDim]: ...

    @property
    def length_squared(self) -> Scalar[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> Scalar[D.Angle]: ...

    @property
    def delta(self) -> Scalar[D.Angle]: ...

    @overload
    def dot(self: Vector3[D.Dimless], o: Vector3[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def dot(self: Vector3[D.Dimless], o: Vector3[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...

    @overload
    def dot(self: Vector3[SomeDim], o: Vector3[D.Dimless]) -> Scalar[SomeDim]: ...

    def dot(self, o: Vector3[SomeOtherDim]) -> Scalar[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Vector3[D.Dimless], o: Vector3[D.Dimless]) -> Vector3[D.Dimless]: ...

    @overload
    def cross(self: Vector3[D.Dimless], o: Vector3[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...

    @overload
    def cross(self: Vector3[SomeDim], o: Vector3[D.Dimless]) -> Vector3[SomeDim]: ...

    @overload
    def cross(self: Vector3[SomeDim], o: Vector3[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    def copy(self) -> Vector3[SomeDim]: ...

    def __pos__(self) -> Vector3[SomeDim]: ...

    def __neg__(self) -> Vector3[SomeDim]: ...

    @overload
    def __radd__(self: Vector3[D.Dimless], o: Number) -> Vector3[D.Dimless]: ...

    @overload
    def __radd__(self: Vector3[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rsub__(self: Vector3[D.Dimless], o: Number) -> Vector3[D.Dimless]: ...

    @overload
    def __rsub__(self: Vector3[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rmul__(self: Vector3[D.Dimless], o: Number) -> Vector3[D.Dimless]: ...

    @overload
    def __rmul__(self: Vector3[SomeDim], o: Number) -> Vector3[SomeDim]: ...

    def __rmul__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rtruediv__(self: Vector3[D.Dimless], o: Number) -> Vector3[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Vector3[SomeDim], o: Number) -> Vector3[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Vector3[Any]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: Scalar[SomeDim],
        y: Scalar[SomeDim],
        z: Scalar[SomeDim],
    ) -> Vector3[SomeDim]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: Number,
        y: Number,
        z: Number,
    ) -> Vector3[D.Dimless]: ...

    @staticmethod
    def from_spherical(
        theta: Scalar[D.Angle],
        delta: Scalar[D.Angle],
        rho: Scalar[SomeOtherDim],
    ) -> Vector3[SomeOtherDim]: ...

    def __add__(self: Vector3[SomeDim], o: Vector3[SomeDim] | Scalar[SomeDim]) -> Vector3[SomeDim]: ...

    def __sub__(self: Vector3[SomeDim], o: Vector3[SomeDim] | Scalar[SomeDim]) -> Vector3[SomeDim]: ...

    @overload
    def __mul__(self: Vector3[D.Dimless], o: Number | Scalar[D.Dimless]) -> Vector3[D.Dimless]: ...

    @overload
    def __mul__(self: Vector3[D.Dimless], o: Scalar[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...

    @overload
    def __mul__(self: Vector3[SomeDim], o: Number | Scalar[D.Dimless]) -> Vector3[SomeDim]: ...

    @overload
    def __mul__(self: Vector3[SomeDim], o: Scalar[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Vector3[D.Dimless], o: Number | Scalar[D.Dimless]) -> Vector3[D.Dimless]: ...

    @overload
    def __truediv__(self: Vector3[D.Dimless], o: Scalar[SomeOtherDim]) -> Vector3[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Vector3[SomeDim], o: Number | Scalar[D.Dimless]) -> Vector3[SomeDim]: ...

    @overload
    def __truediv__(self: Vector3[SomeDim], o: Scalar[SomeOtherDim]) -> Vector3[QuotientDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Vector3[D.Dimless], o: Vector3[D.Dimless]) -> Scalar[D.Dimless]: ...

    @overload
    def __matmul__(self: Vector3[SomeDim], o: Vector3[SomeOtherDim]) -> Scalar[ProductDim[SomeDim, SomeOtherDim]]: ...

    def normalized(self) -> Vector3[D.Dimless]: ...
    
    def angle(self: Vector3[SomeDim], o: Vector3[SomeDim]) -> Scalar[D.Angle]: ...


class Vector3Array(Tensor_V3[SomeDim], Generic[SomeDim]):
    @property
    def size(self) -> int: ...
    
    @property
    def x(self) -> ScalarArray[SomeDim]: ...

    @property
    def y(self) -> ScalarArray[SomeDim]: ...

    @property
    def z(self) -> ScalarArray[SomeDim]: ...

    @property
    def length(self) -> ScalarArray[SomeDim]: ...

    @property
    def length_squared(self) -> ScalarArray[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> ScalarArray[D.Angle]: ...

    @property
    def delta(self) -> ScalarArray[D.Angle]: ...

    @overload
    def dot(self: Vector3Array[D.Dimless], o: Vector3[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def dot(self: Vector3Array[D.Dimless], o: Vector3[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...

    @overload
    def dot(self: Vector3Array[SomeDim], o: Vector3[D.Dimless]) -> ScalarArray[SomeDim]: ...

    def dot(self, o: Vector3[SomeOtherDim]) -> ScalarArray[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Vector3Array[D.Dimless], o: Vector3[D.Dimless]) -> Vector3Array[D.Dimless]: ...

    @overload
    def cross(self: Vector3Array[D.Dimless], o: Vector3[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...

    @overload
    def cross(self: Vector3Array[SomeDim], o: Vector3[D.Dimless]) -> Vector3Array[SomeDim]: ...

    @overload
    def cross(self: Vector3Array[SomeDim], o: Vector3[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...
    def copy(self) -> Vector3Array[SomeDim]: ...

    def __pos__(self) -> Vector3Array[SomeDim]: ...

    def __neg__(self) -> Vector3Array[SomeDim]: ...

    @overload
    def __radd__(self: Vector3Array[D.Dimless], o: Number) -> Vector3Array[D.Dimless]: ...

    @overload
    def __radd__(self: Vector3Array[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Vector3Array[Any]: ...

    @overload
    def __rsub__(self: Vector3Array[D.Dimless], o: Number) -> Vector3Array[D.Dimless]: ...

    @overload
    def __rsub__(self: Vector3Array[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Vector3Array[Any]: ...

    @overload
    def __rmul__(self: Vector3Array[D.Dimless], o: Number) -> Vector3Array[D.Dimless]: ...

    @overload
    def __rmul__(self: Vector3Array[SomeDim], o: Number) -> Vector3Array[SomeDim]: ...

    def __rmul__(self, o: object) -> Vector3Array[Any]: ...

    @overload
    def __rtruediv__(self: Vector3Array[D.Dimless], o: Number) -> Vector3Array[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Vector3Array[SomeDim], o: Number) -> Vector3Array[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Vector3Array[Any]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: ScalarArray[SomeDim],
        y: ScalarArray[SomeDim],
        z: ScalarArray[SomeDim],
    ) -> Vector3Array[SomeDim]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: npt.NDArray[np.floating[Any]],
        y: npt.NDArray[np.floating[Any]],
        z: npt.NDArray[np.floating[Any]],
    ) -> Vector3Array[D.Dimless]: ...

    @staticmethod
    def from_spherical(
        theta: ScalarArray[D.Angle],
        delta: ScalarArray[D.Angle],
        rho: ScalarArray[SomeOtherDim],
    ) -> Vector3Array[SomeOtherDim]: ...

    @staticmethod
    def from_vectors(*vectors: Vector3[SomeDim]) -> Vector3Array[SomeDim]: ...

    def __getitem__(self: Vector3Array[SomeDim], index: int) -> Vector3[SomeDim]: ...

    def __add__(self: Vector3Array[SomeDim], o: Vector3Array[SomeDim] | ScalarArray[SomeDim]) -> Vector3Array[SomeDim]: ...

    def __sub__(self: Vector3Array[SomeDim], o: Vector3Array[SomeDim] | ScalarArray[SomeDim]) -> Vector3Array[SomeDim]: ...

    @overload
    def __mul__(self: Vector3Array[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> Vector3Array[D.Dimless]: ...

    @overload
    def __mul__(self: Vector3Array[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...

    @overload
    def __mul__(self: Vector3Array[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> Vector3Array[SomeDim]: ...

    @overload
    def __mul__(self: Vector3Array[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Vector3Array[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> Vector3Array[D.Dimless]: ...

    @overload
    def __truediv__(self: Vector3Array[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> Vector3Array[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Vector3Array[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless]) -> Vector3Array[SomeDim]: ...

    @overload
    def __truediv__(self: Vector3Array[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> Vector3Array[QuotientDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Vector3Array[D.Dimless], o: Vector3[D.Dimless]) -> ScalarArray[D.Dimless]: ...

    @overload
    def __matmul__(self: Vector3Array[SomeDim], o: Vector3[SomeOtherDim]) -> ScalarArray[ProductDim[SomeDim, SomeOtherDim]]: ...

    def normalized(self) -> Vector3Array[D.Dimless]: ...
    
    def angle(self: Vector3Array[SomeDim], o: Vector3Array[SomeDim]) -> ScalarArray[D.Angle]: ...


class Matrix33(Tensor_M33[SomeDim], Generic[SomeDim]):
    def cast(self, dim: type[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...
    def copy(self) -> Matrix33[SomeDim]: ...

    def __pos__(self) -> Matrix33[SomeDim]: ...

    def __neg__(self) -> Matrix33[SomeDim]: ...    

    @overload
    def __radd__(self: Matrix33[D.Dimless], o: Number) -> Matrix33[D.Dimless]: ...

    @overload
    def __radd__(self: Matrix33[SomeDim], o: Number) -> Never: ...

    def __radd__(self, o: object) -> Matrix33[Any]: ...

    @overload
    def __rsub__(self: Matrix33[D.Dimless], o: Number) -> Matrix33[D.Dimless]: ...

    @overload
    def __rsub__(self: Matrix33[SomeDim], o: Number) -> Never: ...

    def __rsub__(self, o: object) -> Matrix33[Any]: ...

    @overload
    def __rmul__(self: Matrix33[D.Dimless], o: Number) -> Matrix33[D.Dimless]: ...

    @overload
    def __rmul__(self: Matrix33[SomeDim], o: Number) -> Matrix33[SomeDim]: ...

    def __rmul__(self, o: object) -> Matrix33[Any]: ...

    @overload
    def __rtruediv__(self: Matrix33[D.Dimless], o: Number) -> Matrix33[D.Dimless]: ...

    @overload
    def __rtruediv__(self: Matrix33[SomeDim], o: Number) -> Matrix33[QuotientDim[D.Dimless, SomeDim]]: ...

    def __rtruediv__(self, o: object) -> Matrix33[Any]: ...
    @overload
    @classmethod
    def from_elements(
        cls,
        a: Scalar[SomeDim], b: Scalar[SomeDim], c: Scalar[SomeDim],
        d: Scalar[SomeDim], e: Scalar[SomeDim], f: Scalar[SomeDim],
        g: Scalar[SomeDim], h: Scalar[SomeDim], i: Scalar[SomeDim],
    ) -> Matrix33[SomeDim]: ...

    @overload
    @classmethod
    def from_elements(
        cls,
        a: Number, b: Number, c: Number,
        d: Number, e: Number, f: Number,
        g: Number, h: Number, i: Number,
    ) -> Matrix33[D.Dimless]: ...

    @overload
    def inverse(self: Matrix33[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def inverse(self: Matrix33[SomeDim]) -> Matrix33[QuotientDim[D.Dimless, SomeDim]]: ...

    @overload
    def __add__(self: Matrix33[D.Dimless], o: Matrix33[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def __add__(self: Matrix33[SomeDim], o: Matrix33[SomeDim] | Scalar[SomeDim]) -> Matrix33[SomeDim]: ...

    @overload
    def __sub__(self: Matrix33[D.Dimless], o: Matrix33[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def __sub__(self: Matrix33[SomeDim], o: Matrix33[SomeDim] | Scalar[SomeDim]) -> Matrix33[SomeDim]: ...

    @overload
    def __mul__(self: Matrix33[D.Dimless], o: Number | Scalar[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def __mul__(self: Matrix33[D.Dimless], o: Scalar[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...

    @overload
    def __mul__(self: Matrix33[SomeDim], o: Number | Scalar[D.Dimless]) -> Matrix33[SomeDim]: ...

    @overload
    def __mul__(self: Matrix33[SomeDim], o: Scalar[SomeOtherDim]) -> Matrix33[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Matrix33[D.Dimless], o: Number | Scalar[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def __truediv__(self: Matrix33[D.Dimless], o: Scalar[SomeOtherDim]) -> Matrix33[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Matrix33[SomeDim], o: Number | Scalar[D.Dimless]) -> Matrix33[SomeDim]: ...

    @overload
    def __truediv__(self: Matrix33[SomeDim], o: Scalar[SomeOtherDim]) -> Matrix33[QuotientDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Matrix33[D.Dimless]) -> Matrix33[D.Dimless]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Matrix33[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...

    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Matrix33[SomeOtherDim]) -> Matrix33[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Tensor_V3[D.Dimless]) -> Tensor_V3[D.Dimless]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...

    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Tensor_V3[D.Dimless]) -> Tensor_V3[SomeDim]: ...

    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Vector3[D.Dimless]) -> Vector3[D.Dimless]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Vector3[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...

    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Vector3[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Vector3Array[D.Dimless]) -> Vector3Array[D.Dimless]: ...

    @overload
    def __matmul__(self: Matrix33[D.Dimless], o: Vector3Array[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...

    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Vector3Array[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...


class Matrix33Array(Tensor_M33[SomeDim], Generic[SomeDim]):
    @property
    def size(self) -> int: ...

    def cast(self, dim: type[SomeOtherDim]) -> Matrix33Array[SomeOtherDim]: ...
    def copy(self) -> Matrix33Array[SomeDim]: ...

    def __pos__(self) -> Matrix33Array[SomeDim]: ...

    def __neg__(self) -> Matrix33Array[SomeDim]: ...

    def __getitem__(self: Matrix33Array[SomeDim], index: int) -> Matrix33[SomeDim]: ...

    @overload
    def inverse(self: Matrix33Array[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def inverse(self: Matrix33Array[SomeDim]) -> Matrix33Array[QuotientDim[D.Dimless, SomeDim]]: ...

    @overload
    def __add__(self: Matrix33Array[D.Dimless], o: Matrix33Array[D.Dimless] | Matrix33[D.Dimless] | ScalarArray[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def __add__(self: Matrix33Array[SomeDim], o: Matrix33Array[SomeDim] | Matrix33[SomeDim] | ScalarArray[SomeDim]) -> Matrix33Array[SomeDim]: ...

    @overload
    def __sub__(self: Matrix33Array[D.Dimless], o: Matrix33Array[D.Dimless] | Matrix33[D.Dimless] | ScalarArray[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def __sub__(self: Matrix33Array[SomeDim], o: Matrix33Array[SomeDim] | Matrix33[SomeDim] | ScalarArray[SomeDim]) -> Matrix33Array[SomeDim]: ...

    @overload
    def __mul__(self: Matrix33Array[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless] | Matrix33Array[D.Dimless] | Matrix33[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def __mul__(self: Matrix33Array[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Matrix33Array[SomeOtherDim]: ...

    @overload
    def __mul__(self: Matrix33Array[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless] | Matrix33Array[D.Dimless] | Matrix33[D.Dimless]) -> Matrix33Array[SomeDim]: ...

    @overload
    def __mul__(self: Matrix33Array[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Matrix33Array[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Matrix33Array[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless] | Matrix33Array[D.Dimless] | Matrix33[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def __truediv__(self: Matrix33Array[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Matrix33Array[QuotientDim[D.Dimless, SomeOtherDim]]: ...

    @overload
    def __truediv__(self: Matrix33Array[SomeDim], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless] | Matrix33Array[D.Dimless] | Matrix33[D.Dimless]) -> Matrix33Array[SomeDim]: ...

    @overload
    def __truediv__(self: Matrix33Array[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Matrix33Array[QuotientDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def __mod__(self: Matrix33Array[D.Dimless], o: Number | Scalar[D.Dimless] | ScalarArray[D.Dimless] | Matrix33Array[D.Dimless] | Matrix33[D.Dimless]) -> Matrix33Array[D.Dimless]: ...

    @overload
    def __mod__(self: Matrix33Array[D.Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Never: ...

    @overload
    def __mod__(self: Matrix33Array[SomeDim], o: Number) -> Never: ...

    @overload
    def __mod__(self: Matrix33Array[SomeDim], o: Scalar[SomeDim] | ScalarArray[SomeDim] | Matrix33Array[SomeDim] | Matrix33[SomeDim]) -> Matrix33Array[SomeDim]: ...

    @overload
    def __mod__(self: Matrix33Array[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim] | Matrix33Array[SomeOtherDim] | Matrix33[SomeOtherDim]) -> Never: ...

    @overload
    def __matmul__(self: Matrix33Array[D.Dimless], o: Vector3Array[D.Dimless]) -> Vector3Array[D.Dimless]: ...

    @overload
    def __matmul__(self: Matrix33Array[D.Dimless], o: Vector3Array[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...

    @overload
    def __matmul__(self: Matrix33Array[SomeDim], o: Vector3Array[D.Dimless]) -> Vector3Array[SomeDim]: ...

    @overload
    def __matmul__(self: Matrix33Array[SomeDim], o: Vector3Array[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...


def ensure_tensor(o: Any | Tensor[SomeDim]) -> Tensor[SomeDim] | Tensor[D.Dimless]: ...

def ensure_same_dimensions(*tensors: Tensor[Any]) -> Literal[True]: ...

@overload
def abs(tensor: Scalar[SomeDim]) -> Scalar[SomeDim]: ...

@overload
def abs(tensor: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...

@overload
def abs(tensor: Vector3[SomeDim]) -> Vector3[SomeDim]: ...

@overload
def abs(tensor: Vector3Array[SomeDim]) -> Vector3Array[SomeDim]: ...

@overload
def abs(tensor: Matrix33[SomeDim]) -> Matrix33[SomeDim]: ...

@overload
def abs(tensor: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...

@overload
def abs(tensor: Tensor_V3[SomeDim]) -> Tensor_V3[SomeDim]: ...

@overload
def abs(tensor: Tensor_M33[SomeDim]) -> Tensor_M33[SomeDim]: ...

def abs(tensor: Tensor[Any]) -> Tensor[Any]: ...

@overload
def square(tensor: Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

@overload
def square(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

@overload
def square(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

@overload
def square(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P2, P1]]: ...

@overload
def square(tensor: Scalar[PowerDim[SomeDim, P1, P2]]) -> Scalar[SomeDim]: ...

@overload
def square(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P2, P1]]: ...

@overload
def square(tensor: ScalarArray[PowerDim[SomeDim, P1, P2]]) -> ScalarArray[SomeDim]: ...

@overload
def square(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P2, P1]]: ...

@overload
def square(tensor: Tensor_S[PowerDim[SomeDim, P1, P2]]) -> Tensor_S[SomeDim]: ...

def square(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cube(tensor: Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

@overload
def cube(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

@overload
def cube(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

@overload
def cube(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P3, P1]]: ...

@overload
def cube(tensor: Scalar[PowerDim[SomeDim, P1, P3]]) -> Scalar[SomeDim]: ...

@overload
def cube(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P3, P1]]: ...

@overload
def cube(tensor: ScalarArray[PowerDim[SomeDim, P1, P3]]) -> ScalarArray[SomeDim]: ...

@overload
def cube(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P3, P1]]: ...

@overload
def cube(tensor: Tensor_S[PowerDim[SomeDim, P1, P3]]) -> Tensor_S[SomeDim]: ...

def cube(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def sqrt(tensor: Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

@overload
def sqrt(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

@overload
def sqrt(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

@overload
def sqrt(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P1, P2]]: ...

@overload
def sqrt(tensor: Scalar[PowerDim[SomeDim, P2, P1]]) -> Scalar[SomeDim]: ...

@overload
def sqrt(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P1, P2]]: ...

@overload
def sqrt(tensor: ScalarArray[PowerDim[SomeDim, P2, P1]]) -> ScalarArray[SomeDim]: ...

@overload
def sqrt(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P1, P2]]: ...

@overload
def sqrt(tensor: Tensor_S[PowerDim[SomeDim, P2, P1]]) -> Tensor_S[SomeDim]: ...

def sqrt(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cbrt(tensor: Scalar[D.Dimless]) -> Scalar[D.Dimless]: ...

@overload
def cbrt(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Dimless]: ...

@overload
def cbrt(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Dimless]: ...

@overload
def cbrt(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P1, P3]]: ...

@overload
def cbrt(tensor: Scalar[PowerDim[SomeDim, P3, P1]]) -> Scalar[SomeDim]: ...

@overload
def cbrt(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P1, P3]]: ...

@overload
def cbrt(tensor: ScalarArray[PowerDim[SomeDim, P3, P1]]) -> ScalarArray[SomeDim]: ...

@overload
def cbrt(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P1, P3]]: ...

@overload
def cbrt(tensor: Tensor_S[PowerDim[SomeDim, P3, P1]]) -> Tensor_S[SomeDim]: ...

def cbrt(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cos(tensor: Scalar[D.Angle]) -> Scalar[D.Dimless]: ...

@overload
def cos(tensor: ScalarArray[D.Angle]) -> ScalarArray[D.Dimless]: ...

@overload
def cos(tensor: Tensor_S[D.Angle]) -> Tensor_S[D.Dimless]: ...

def cos(tensor: Tensor[D.Angle]) -> Tensor[D.Dimless]: ...


@overload
def sin(tensor: Scalar[D.Angle]) -> Scalar[D.Dimless]: ...

@overload
def sin(tensor: ScalarArray[D.Angle]) -> ScalarArray[D.Dimless]: ...

@overload
def sin(tensor: Tensor_S[D.Angle]) -> Tensor_S[D.Dimless]: ...

def sin(tensor: Tensor[D.Angle]) -> Tensor[D.Dimless]: ...


@overload
def tan(tensor: Scalar[D.Angle]) -> Scalar[D.Dimless]: ...

@overload
def tan(tensor: ScalarArray[D.Angle]) -> ScalarArray[D.Dimless]: ...

@overload
def tan(tensor: Tensor_S[D.Angle]) -> Tensor_S[D.Dimless]: ...

def tan(tensor: Tensor[D.Angle]) -> Tensor[D.Dimless]: ...


@overload
def acos(tensor: Scalar[D.Dimless]) -> Scalar[D.Angle]: ...

@overload
def acos(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Angle]: ...

@overload
def acos(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Angle]: ...

def acos(tensor: Tensor[D.Dimless]) -> Tensor[D.Angle]: ...


@overload
def asin(tensor: Scalar[D.Dimless]) -> Scalar[D.Angle]: ...

@overload
def asin(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Angle]: ...

@overload
def asin(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Angle]: ...

def asin(tensor: Tensor[D.Dimless]) -> Tensor[D.Angle]: ...


@overload
def atan(tensor: Scalar[D.Dimless]) -> Scalar[D.Angle]: ...

@overload
def atan(tensor: ScalarArray[D.Dimless]) -> ScalarArray[D.Angle]: ...

@overload
def atan(tensor: Tensor_S[D.Dimless]) -> Tensor_S[D.Angle]: ...

def atan(tensor: Tensor[D.Dimless]) -> Tensor[D.Angle]: ...


@overload
def atan2(y: Scalar[SomeDim], x: Scalar[SomeDim]) -> Scalar[D.Angle]: ...

@overload
def atan2(y: ScalarArray[SomeDim], x: ScalarArray[SomeDim]) -> ScalarArray[D.Angle]: ...

@overload
def atan2(y: Tensor_S[SomeDim], x: Tensor_S[SomeDim]) -> Tensor_S[D.Angle]: ...

def atan2(y: Tensor[SomeDim], x: Tensor[SomeDim]) -> Tensor[D.Angle]: ...


@overload
def normalize_angle(angle: Scalar[D.Angle]) -> Scalar[D.Angle]: ...

@overload
def normalize_angle(angle: ScalarArray[D.Angle]) -> ScalarArray[D.Angle]: ...

def normalize_angle(angle: Tensor[D.Angle]) -> Tensor[D.Angle]: ...


@overload
def normalize_angle_symmetric(angle: Scalar[D.Angle]) -> Scalar[D.Angle]: ...

@overload
def normalize_angle_symmetric(angle: ScalarArray[D.Angle]) -> ScalarArray[D.Angle]: ...

def normalize_angle_symmetric(angle: Tensor[D.Angle]) -> Tensor[D.Angle]: ...


@overload
def interpolate(t1: Scalar[SomeDim], t2: Scalar[SomeDim], alpha: Number) -> Scalar[SomeDim]: ...

@overload
def interpolate(t1: ScalarArray[SomeDim], t2: ScalarArray[SomeDim], alpha: Number) -> ScalarArray[SomeDim]: ...

@overload
def interpolate(t1: Vector3[SomeDim], t2: Vector3[SomeDim], alpha: Number) -> Vector3[SomeDim]: ...

@overload
def interpolate(t1: Vector3Array[SomeDim], t2: Vector3Array[SomeDim], alpha: Number) -> Vector3Array[SomeDim]: ...

@overload
def interpolate(t1: Matrix33[SomeDim], t2: Matrix33[SomeDim], alpha: Number) -> Matrix33[SomeDim]: ...

@overload
def interpolate(t1: Matrix33Array[SomeDim], t2: Matrix33Array[SomeDim], alpha: Number) -> Matrix33Array[SomeDim]: ...

@overload
def interpolate(t1: Tensor_S[SomeDim], t2: Tensor_S[SomeDim], alpha: Number) -> Tensor_S[SomeDim]: ...

@overload
def interpolate(t1: Tensor_V3[SomeDim], t2: Tensor_V3[SomeDim], alpha: Number) -> Tensor_V3[SomeDim]: ...

@overload
def interpolate(t1: Tensor_M33[SomeDim], t2: Tensor_M33[SomeDim], alpha: Number) -> Tensor_M33[SomeDim]: ...

def interpolate(t1: Tensor[SomeDim], t2: Tensor[SomeDim], alpha: Number) -> Tensor[SomeDim]: ...


class QuantityMeta(type):
    def __getattr__(cls, name: str) -> Scalar: ...


class Quantity(metaclass=QuantityMeta):
    @classmethod
    def get(cls, value: str) -> Scalar: ...

    # ANGLES
    rad: Scalar[D.Angle]
    deg: Scalar[D.Angle]

    # DISTANCES
    meter: Scalar[D.Length]
    kilo_meter: Scalar[D.Length]
    radii_earth: Scalar[D.Length]
    radii_sun: Scalar[D.Length]

    # DURATIONS
    second: Scalar[D.Time]
    minute: Scalar[D.Time]
    hour: Scalar[D.Time]
    day: Scalar[D.Time]
    month: Scalar[D.Time]
    year: Scalar[D.Time]

