from __future__ import annotations

from fractions import Fraction
from typing import Any, ClassVar, Generic, Literal, TypeAlias, TypeVar, overload

import numpy as np
import numpy.typing as npt

Number: TypeAlias = float | int | np.floating[Any]
TensorData: TypeAlias = npt.NDArray[np.float64]


class DimTriplet:
    length: Fraction
    time: Fraction
    mass: Fraction
    dimensionless: bool

    def __init__(
        self,
        length: Fraction | int = 0,
        time: Fraction | int = 0,
        mass: Fraction | int = 0,
    ) -> None: ...

    @property
    def representation(self) -> str: ...

    def __mul__(self, o: DimTriplet) -> DimTriplet: ...
    def __truediv__(self, o: DimTriplet) -> DimTriplet: ...
    def __pow__(self, p: Fraction | int | float) -> DimTriplet: ...


class _DimClassAlgebra(type):
    def __mul__(cls, o: type[Dim]) -> type[Dim]: ...
    def __truediv__(cls, o: type[Dim]) -> type[Dim]: ...
    def __rtruediv__(cls, o: Literal[1]) -> type[Dim]: ...
    def __pow__(cls, p: Fraction | int | float) -> type[Dim]: ...


class Dim(metaclass=_DimClassAlgebra):
    @classmethod
    def triplet(cls) -> DimTriplet: ...


class Dimless(Dim): ...
Angle = Dimless

class Length(Dim): ...
class Time(Dim): ...
class Mass(Dim): ...
class Velocity(Dim): ...
class Acceleration(Dim): ...
class Force(Dim): ...
class Frequency(Dim): ...
AngularVelocity = Frequency


SomeDim = TypeVar("SomeDim", bound=Dim)
SomeOtherDim = TypeVar("SomeOtherDim", bound=Dim)


class Tensor(Generic[SomeDim]):
    _values: TensorData
    _dim: ClassVar[type[Dim]]
    _base_tensor_class: ClassVar[type[Tensor[Any]]]

    def __init__(self, values: Number | TensorData) -> None: ...

    @property
    def dim_triplet(self) -> DimTriplet: ...

    @property
    def dim(self) -> type[SomeDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor[SomeOtherDim]: ...
    def copy(self) -> Tensor[SomeDim]: ...
    def ensure_compatible_dimensions(self, o: Tensor[Any]) -> bool: ...
    def check(self, dim: type[Dim]) -> bool: ...
    def get_raw_array(self, units: str = "1") -> npt.NDArray[np.float64]: ...

    def __pos__(self) -> Tensor[SomeDim]: ...
    def __neg__(self) -> Tensor[SomeDim]: ...

    def __add__(self, o: object) -> Tensor[Any]: ...
    def __radd__(self, o: object) -> Tensor[Any]: ...
    def __sub__(self, o: object) -> Tensor[Any]: ...
    def __rsub__(self, o: object) -> Tensor[Any]: ...
    def __mul__(self, o: object) -> Tensor[Any]: ...
    def __rmul__(self, o: object) -> Tensor[Any]: ...
    def __truediv__(self, o: object) -> Tensor[Any]: ...
    def __rtruediv__(self, o: object) -> Tensor[Any]: ...
    def __matmul__(self, o: object) -> Tensor[Any]: ...
    def __rmatmul__(self, o: object) -> Tensor[Any]: ...
    def __mod__(self, o: object) -> Tensor[Any]: ...
    def __rmod__(self, o: object) -> Tensor[Any]: ...


class Tensor_S(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> Number | npt.NDArray[np.float64]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...
    def copy(self) -> Tensor_S[SomeDim]: ...
    def magnitude(self, units: str = "1") -> Number | npt.NDArray[np.float64]: ...

    def __getitem__(self, index: int) -> Scalar[SomeDim]: ...

    def __lt__(self, o: object) -> bool: ...
    def __le__(self, o: object) -> bool: ...
    def __gt__(self, o: object) -> bool: ...
    def __ge__(self, o: object) -> bool: ...

    def __add__(self, o: object) -> Tensor_S[Any]: ...
    def __radd__(self, o: object) -> Tensor_S[Any]: ...
    def __sub__(self, o: object) -> Tensor_S[Any]: ...
    def __rsub__(self, o: object) -> Tensor_S[Any]: ...
    def __mul__(self, o: object) -> Tensor_S[Any]: ...
    def __rmul__(self, o: object) -> Tensor_S[Any]: ...
    def __truediv__(self, o: object) -> Tensor_S[Any]: ...
    def __rtruediv__(self, o: object) -> Tensor_S[Any]: ...
    def __mod__(self, o: object) -> Tensor_S[Any]: ...
    def __rmod__(self, o: object) -> Tensor_S[Any]: ...


class Tensor_V3(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_components(
        cls,
        x: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
        y: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
        z: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
    ) -> Tensor_V3[SomeDim]: ...

    @staticmethod
    def from_spherical(
        theta: Tensor_S[Angle],
        delta: Tensor_S[Angle],
        rho: Tensor_S[SomeOtherDim],
    ) -> Tensor_V3[SomeOtherDim]: ...

    @staticmethod
    def from_vectors(*vectors: Vector3[SomeDim]) -> Vector3Array[SomeDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    def copy(self) -> Tensor_V3[SomeDim]: ...

    def dot(self, o: Tensor_V3[Any]) -> Tensor_S[Any]: ...
    def cross(self, o: Tensor_V3[Any]) -> Tensor_V3[Any]: ...

    @property
    def size(self) -> int: ...

    @property
    def x(self) -> Tensor_S[SomeDim]: ...

    @property
    def y(self) -> Tensor_S[SomeDim]: ...

    @property
    def z(self) -> Tensor_S[SomeDim]: ...

    @property
    def length(self) -> Tensor_S[Any]: ...

    @property
    def length_squared(self) -> Tensor_S[Any]: ...

    @property
    def theta(self) -> Tensor_S[Angle]: ...

    @property
    def delta(self) -> Tensor_S[Angle]: ...

    def angle(self, o: Tensor_V3[SomeDim]) -> Tensor_S[Angle]: ...
    def normalized(self) -> Tensor_V3[Any]: ...
    def __getitem__(self, index: int) -> Vector3[SomeDim]: ...

    def __add__(self, o: object) -> Tensor_V3[Any]: ...
    def __radd__(self, o: object) -> Tensor_V3[Any]: ...
    def __sub__(self, o: object) -> Tensor_V3[Any]: ...
    def __rsub__(self, o: object) -> Tensor_V3[Any]: ...
    def __mul__(self, o: object) -> Tensor_V3[Any]: ...
    def __rmul__(self, o: object) -> Tensor_V3[Any]: ...
    def __truediv__(self, o: object) -> Tensor_V3[Any]: ...
    def __rtruediv__(self, o: object) -> Tensor_V3[Any]: ...
    def __matmul__(self, o: object) -> Tensor_S[Any]: ...
    def __rmatmul__(self, o: object) -> Tensor_S[Any]: ...
    def __mod__(self, o: object) -> Tensor_V3[Any]: ...
    def __rmod__(self, o: object) -> Tensor_V3[Any]: ...


class Tensor_M33(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_elements(
        cls,
        a: Tensor_S[SomeDim] | Number,
        b: Tensor_S[SomeDim] | Number,
        c: Tensor_S[SomeDim] | Number,
        d: Tensor_S[SomeDim] | Number,
        e: Tensor_S[SomeDim] | Number,
        f: Tensor_S[SomeDim] | Number,
        g: Tensor_S[SomeDim] | Number,
        h: Tensor_S[SomeDim] | Number,
        i: Tensor_S[SomeDim] | Number,
    ) -> Tensor_M33[SomeDim]: ...

    @property
    def size(self) -> int: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_M33[SomeOtherDim]: ...
    def copy(self) -> Tensor_M33[SomeDim]: ...
    def inverse(self) -> Tensor_M33[Any]: ...
    def __getitem__(self, index: int) -> Matrix33[SomeDim]: ...

    def __add__(self, o: object) -> Tensor_M33[Any]: ...
    def __radd__(self, o: object) -> Tensor_M33[Any]: ...
    def __sub__(self, o: object) -> Tensor_M33[Any]: ...
    def __rsub__(self, o: object) -> Tensor_M33[Any]: ...
    def __mul__(self, o: object) -> Tensor_M33[Any]: ...
    def __rmul__(self, o: object) -> Tensor_M33[Any]: ...
    def __truediv__(self, o: object) -> Tensor_M33[Any]: ...
    def __rtruediv__(self, o: object) -> Tensor_M33[Any]: ...
    def __matmul__(self, o: object) -> Tensor[Any]: ...
    def __rmatmul__(self, o: object) -> Tensor[Any]: ...
    def __mod__(self, o: object) -> Tensor_M33[Any]: ...
    def __rmod__(self, o: object) -> Tensor_M33[Any]: ...


class Scalar(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, value: Number) -> None: ...

    @property
    def base_unit_value(self) -> Number: ...

    def magnitude(self, units: str = "1") -> Number: ...
    def cast(self, dim: type[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...
    def copy(self) -> Scalar[SomeDim]: ...


class ScalarArray(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, values: npt.NDArray[np.float64]) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> npt.NDArray[np.float64]: ...

    def magnitude(self, units: str = "1") -> npt.NDArray[np.float64]: ...
    def cast(self, dim: type[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...
    def copy(self) -> ScalarArray[SomeDim]: ...
    def __getitem__(self, index: int) -> Scalar[SomeDim]: ...


class Vector3(Tensor_V3[SomeDim], Generic[SomeDim]):
    O: ClassVar[Vector3[Dimless]]
    X: ClassVar[Vector3[Dimless]]
    Y: ClassVar[Vector3[Dimless]]
    Z: ClassVar[Vector3[Dimless]]

    @overload
    @classmethod
    def from_components(
        cls,
        x: Scalar[SomeDim],
        y: Scalar[SomeDim],
        z: Scalar[SomeDim],
    ) -> Vector3[SomeDim]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: Number,
        y: Number,
        z: Number,
    ) -> Vector3[Dimless]: ...

    @staticmethod
    def from_spherical(
        theta: Scalar[Angle],
        delta: Scalar[Angle],
        rho: Scalar[SomeOtherDim],
    ) -> Vector3[SomeOtherDim]: ...

    @property
    def x(self) -> Scalar[SomeDim]: ...

    @property
    def y(self) -> Scalar[SomeDim]: ...

    @property
    def z(self) -> Scalar[SomeDim]: ...

    @property
    def length(self) -> Scalar[Any]: ...

    @property
    def length_squared(self) -> Scalar[Any]: ...

    @property
    def theta(self) -> Scalar[Angle]: ...

    @property
    def delta(self) -> Scalar[Angle]: ...

    def dot(self, o: Vector3[Any]) -> Scalar[Any]: ...
    def cross(self, o: Vector3[Any]) -> Vector3[Any]: ...
    def cast(self, dim: type[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    def copy(self) -> Vector3[SomeDim]: ...
    def angle(self, o: Vector3[SomeDim]) -> Scalar[Angle]: ...
    def normalized(self) -> Vector3[Any]: ...


class Vector3Array(Tensor_V3[SomeDim], Generic[SomeDim]):
    @property
    def x(self) -> ScalarArray[SomeDim]: ...

    @property
    def y(self) -> ScalarArray[SomeDim]: ...

    @property
    def z(self) -> ScalarArray[SomeDim]: ...

    @property
    def length(self) -> ScalarArray[Any]: ...

    @property
    def length_squared(self) -> ScalarArray[Any]: ...

    @property
    def theta(self) -> ScalarArray[Angle]: ...

    @property
    def delta(self) -> ScalarArray[Angle]: ...

    @staticmethod
    def from_vectors(*vectors: Vector3[SomeDim]) -> Vector3Array[SomeDim]: ...

    def dot(self, o: Vector3[Any]) -> ScalarArray[Any]: ...
    def cross(self, o: Vector3[Any]) -> Vector3Array[Any]: ...
    def cast(self, dim: type[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...
    def copy(self) -> Vector3Array[SomeDim]: ...
    def angle(self, o: Vector3Array[SomeDim]) -> ScalarArray[Angle]: ...
    def normalized(self) -> Vector3Array[Any]: ...
    def __getitem__(self, index: int) -> Vector3[SomeDim]: ...


class Matrix33(Tensor_M33[SomeDim], Generic[SomeDim]):
    Id: ClassVar[Matrix33[Dimless]]

    @overload
    @classmethod
    def from_elements(
        cls,
        a: Scalar[SomeDim], b: Scalar[SomeDim], c: Scalar[SomeDim],
        d: Scalar[SomeDim], e: Scalar[SomeDim], f: Scalar[SomeDim],
        g: Scalar[SomeDim], h: Scalar[SomeDim], i: Scalar[SomeDim],
    ) -> Matrix33[SomeDim]: ...

    @overload
    @classmethod
    def from_elements(
        cls,
        a: Number, b: Number, c: Number,
        d: Number, e: Number, f: Number,
        g: Number, h: Number, i: Number,
    ) -> Matrix33[Dimless]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...
    def copy(self) -> Matrix33[SomeDim]: ...
    def inverse(self) -> Matrix33[Any]: ...


class Matrix33Array(Tensor_M33[SomeDim], Generic[SomeDim]):
    def cast(self, dim: type[SomeOtherDim]) -> Matrix33Array[SomeOtherDim]: ...
    def copy(self) -> Matrix33Array[SomeDim]: ...
    def inverse(self) -> Matrix33Array[Any]: ...
    def __getitem__(self, index: int) -> Matrix33[SomeDim]: ...


def ensure_tensor(o: Any | Tensor[SomeDim]) -> Tensor[Any]: ...
def ensure_same_dimensions(*tensors: Tensor[Any]) -> Literal[True]: ...


@overload
def abs(tensor: Scalar[SomeDim]) -> Scalar[SomeDim]: ...
@overload
def abs(tensor: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
@overload
def abs(tensor: Vector3[SomeDim]) -> Vector3[SomeDim]: ...
@overload
def abs(tensor: Vector3Array[SomeDim]) -> Vector3Array[SomeDim]: ...
@overload
def abs(tensor: Matrix33[SomeDim]) -> Matrix33[SomeDim]: ...
@overload
def abs(tensor: Matrix33Array[SomeDim]) -> Matrix33Array[SomeDim]: ...
@overload
def abs(tensor: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...
@overload
def abs(tensor: Tensor_V3[SomeDim]) -> Tensor_V3[SomeDim]: ...
@overload
def abs(tensor: Tensor_M33[SomeDim]) -> Tensor_M33[SomeDim]: ...
def abs(tensor: Tensor[Any]) -> Tensor[Any]: ...


def square(tensor: Tensor[Any]) -> Tensor[Any]: ...
def cube(tensor: Tensor[Any]) -> Tensor[Any]: ...
def sqrt(tensor: Tensor[Any]) -> Tensor[Any]: ...
def cbrt(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cos(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def cos(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def cos(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def cos(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...

@overload
def sin(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def sin(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def sin(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def sin(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...

@overload
def tan(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def tan(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def tan(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def tan(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...

@overload
def acos(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def acos(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def acos(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def acos(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...

@overload
def asin(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def asin(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def asin(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def asin(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...

@overload
def atan(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def atan(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def atan(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def atan(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...

@overload
def atan2(y: Scalar[SomeDim], x: Scalar[SomeDim]) -> Scalar[Angle]: ...
@overload
def atan2(y: ScalarArray[SomeDim], x: ScalarArray[SomeDim]) -> ScalarArray[Angle]: ...
@overload
def atan2(y: Tensor_S[SomeDim], x: Tensor_S[SomeDim]) -> Tensor_S[Angle]: ...
def atan2(y: Tensor[SomeDim], x: Tensor[SomeDim]) -> Tensor[Angle]: ...

@overload
def normalize_angle(angle: Scalar[Angle]) -> Scalar[Angle]: ...
@overload
def normalize_angle(angle: ScalarArray[Angle]) -> ScalarArray[Angle]: ...
def normalize_angle(angle: Tensor[Angle]) -> Tensor[Angle]: ...

@overload
def normalize_angle_symmetric(angle: Scalar[Angle]) -> Scalar[Angle]: ...
@overload
def normalize_angle_symmetric(angle: ScalarArray[Angle]) -> ScalarArray[Angle]: ...
def normalize_angle_symmetric(angle: Tensor[Angle]) -> Tensor[Angle]: ...

@overload
def interpolate(t1: Scalar[SomeDim], t2: Scalar[SomeDim], alpha: Number) -> Scalar[SomeDim]: ...
@overload
def interpolate(t1: ScalarArray[SomeDim], t2: ScalarArray[SomeDim], alpha: Number) -> ScalarArray[SomeDim]: ...
@overload
def interpolate(t1: Vector3[SomeDim], t2: Vector3[SomeDim], alpha: Number) -> Vector3[SomeDim]: ...
@overload
def interpolate(t1: Vector3Array[SomeDim], t2: Vector3Array[SomeDim], alpha: Number) -> Vector3Array[SomeDim]: ...
@overload
def interpolate(t1: Matrix33[SomeDim], t2: Matrix33[SomeDim], alpha: Number) -> Matrix33[SomeDim]: ...
@overload
def interpolate(t1: Matrix33Array[SomeDim], t2: Matrix33Array[SomeDim], alpha: Number) -> Matrix33Array[SomeDim]: ...
@overload
def interpolate(t1: Tensor_S[SomeDim], t2: Tensor_S[SomeDim], alpha: Number) -> Tensor_S[SomeDim]: ...
@overload
def interpolate(t1: Tensor_V3[SomeDim], t2: Tensor_V3[SomeDim], alpha: Number) -> Tensor_V3[SomeDim]: ...
@overload
def interpolate(t1: Tensor_M33[SomeDim], t2: Tensor_M33[SomeDim], alpha: Number) -> Tensor_M33[SomeDim]: ...
def interpolate(t1: Tensor[SomeDim], t2: Tensor[SomeDim], alpha: Number) -> Tensor[SomeDim]: ...


class QuantityMeta(type):
    def __getattr__(cls, name: str) -> Scalar[Any]: ...


class Quantity(metaclass=QuantityMeta):
    @classmethod
    def get(cls, value: str) -> Scalar[Any]: ...

    # DIMENSIONLESS
    dimensionless: Scalar[Dimless]

    # ANGLES
    radian: Scalar[Angle]
    turn: Scalar[Angle]
    degree: Scalar[Angle]

    # DISTANCES
    meter: Scalar[Length]
    kilo_meter: Scalar[Length]
    radii_earth: Scalar[Length]
    radii_sun: Scalar[Length]
    astronomical_unit: Scalar[Length]

    # DURATIONS
    second: Scalar[Time]
    minute: Scalar[Time]
    hour: Scalar[Time]
    day: Scalar[Time]
    month: Scalar[Time]
    year: Scalar[Time]

    # MASSES
    kilo_gram: Scalar[Mass]
    gram: Scalar[Mass]
    metric_ton: Scalar[Mass]
