from __future__ import annotations

from fractions import Fraction
from typing import Any, ClassVar, Generic, Literal, Never, TypeAlias, TypeVar, overload

import numpy as np
import numpy.typing as npt

Number: TypeAlias = float | int | np.floating[Any]
TensorData: TypeAlias = npt.NDArray[np.float64]


class DimTriplet:
    length: Fraction
    time: Fraction
    mass: Fraction
    dimensionless: bool

    def __init__(
        self,
        length: Fraction | int = 0,
        time: Fraction | int = 0,
        mass: Fraction | int = 0,
    ) -> None: ...

    @property
    def representation(self) -> str: ...

    def __mul__(self, o: DimTriplet) -> DimTriplet: ...
    def __truediv__(self, o: DimTriplet) -> DimTriplet: ...
    def __pow__(self, p: Fraction | int | float) -> DimTriplet: ...


class _DimClassAlgebra(type):
    def __mul__(cls, o: type[Dim]) -> type[Dim]: ...
    def __truediv__(cls, o: type[Dim]) -> type[Dim]: ...
    def __rtruediv__(cls, o: Literal[1]) -> type[Dim]: ...
    def __pow__(cls, p: Fraction | int | float) -> type[Dim]: ...


class Dim(metaclass=_DimClassAlgebra):
    @classmethod
    def triplet(cls) -> DimTriplet: ...


class Dimless(Dim):
    """L⁰ T⁰ M⁰"""
Angle = Dimless


class Length(Dim):
    """L¹ T⁰ M⁰"""

class Time(Dim):
    """L⁰ T¹ M⁰"""

class Mass(Dim):
    """L⁰ T⁰ M¹"""

class Velocity(Dim):
    """L¹ T⁻¹ M⁰"""

class Acceleration(Dim):
    """L¹ T⁻² M⁰"""

class Force(Dim):
    """L¹ T⁻² M¹"""

class Frequency(Dim):
    """L⁰ T⁻¹ M⁰"""

AngularVelocity = Frequency

class AngularAcceleration(Dim):
    """L⁰ T⁻² M⁰"""

class AngularJerk(Dim):
    """L⁰ T⁻³ M⁰"""

class InvLength(Dim):
    """L⁻¹ T⁰ M⁰"""

ExponentNumerator = TypeVar("ExponentNumerator", bound=int)
ExponentDenominator = TypeVar("ExponentDenominator", bound=int)
SomeDim = TypeVar("SomeDim", bound=Dim)
SomeOtherDim = TypeVar("SomeOtherDim", bound=Dim)


class ProductDim(Dim, Generic[SomeDim, SomeOtherDim]): ...
class QuotientDim(Dim, Generic[SomeDim, SomeOtherDim]): ...
class PowerDim(Dim, Generic[SomeDim, ExponentNumerator, ExponentDenominator]): ...


N4: TypeAlias = Literal[-4]
N3: TypeAlias = Literal[-3]
N2: TypeAlias = Literal[-2]
N1: TypeAlias = Literal[-1]
OO: TypeAlias = Literal[0]
P1: TypeAlias = Literal[1]
P2: TypeAlias = Literal[2]
P3: TypeAlias = Literal[3]
P4: TypeAlias = Literal[4]


class Tensor(Generic[SomeDim]):
    _values: TensorData
    _dim: ClassVar[type[Dim]]
    _base_tensor_class: ClassVar[type[Tensor[Any]]]

    def __init__(self, values: Number | TensorData) -> None: ...

    @property
    def dim_triplet(self) -> DimTriplet: ...

    @property
    def dim_coords(self) -> DimTriplet: ...

    @property
    def dim(self) -> type[SomeDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor[SomeOtherDim]: ...
    def copy(self) -> Tensor[SomeDim]: ...
    def ensure_compatible_dimensions(self, o: Tensor[Any]) -> bool: ...
    def check(self, dim: type[Dim]) -> bool: ...
    def get_raw_array(self, units: str = "1") -> npt.NDArray[np.float64]: ...

    def __pos__(self) -> Tensor[SomeDim]: ...
    def __neg__(self) -> Tensor[SomeDim]: ...

    def __add__(self, o: object) -> Tensor[Any]: ...
    def __radd__(self, o: object) -> Tensor[Any]: ...
    def __sub__(self, o: object) -> Tensor[Any]: ...
    def __rsub__(self, o: object) -> Tensor[Any]: ...
    def __mul__(self, o: object) -> Tensor[Any]: ...
    def __rmul__(self, o: object) -> Tensor[Any]: ...
    def __truediv__(self, o: object) -> Tensor[Any]: ...
    def __rtruediv__(self, o: object) -> Tensor[Any]: ...
    def __matmul__(self, o: object) -> Tensor[Any]: ...
    def __rmatmul__(self, o: object) -> Tensor[Any]: ...
    def __mod__(self, o: object) -> Tensor[Any]: ...
    def __rmod__(self, o: object) -> Tensor[Any]: ...


class Tensor_S(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> Number | npt.NDArray[np.float64]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...
    def copy(self) -> Tensor_S[SomeDim]: ...
    def magnitude(self, units: str = "1") -> Number | npt.NDArray[np.float64]: ...
    def __getitem__(self, index: int) -> Scalar[SomeDim]: ...
    def __pos__(self) -> Tensor_S[SomeDim]: ...
    def __neg__(self) -> Tensor_S[SomeDim]: ...

    @overload
    def __pow__(self: Tensor_S[Dimless], p: N4 | N3 | N2 | N1 | OO | P1 | P2 | P3 | P4) -> Tensor_S[Dimless]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: N4) -> Tensor_S[PowerDim[SomeDim, N4, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: N3) -> Tensor_S[PowerDim[SomeDim, N3, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: N2) -> Tensor_S[PowerDim[SomeDim, N2, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: N1) -> Tensor_S[PowerDim[SomeDim, N1, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: OO) -> Tensor_S[Dimless]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: P1) -> Tensor_S[PowerDim[SomeDim, P1, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: P2) -> Tensor_S[PowerDim[SomeDim, P2, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: P3) -> Tensor_S[PowerDim[SomeDim, P3, P1]]: ...
    @overload
    def __pow__(self: Tensor_S[SomeDim], p: P4) -> Tensor_S[PowerDim[SomeDim, P4, P1]]: ...
    def __pow__(self, p: Fraction | int | float) -> Tensor_S[Any]: ...

    def __lt__(self, o: object) -> bool: ...
    def __le__(self, o: object) -> bool: ...
    def __gt__(self, o: object) -> bool: ...
    def __ge__(self, o: object) -> bool: ...

    @overload
    def __add__(self: Tensor_S[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def __add__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    @overload
    def __add__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...
    def __add__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __sub__(self: Tensor_S[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def __sub__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    @overload
    def __sub__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...
    def __sub__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __mul__(self: Tensor_S[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def __mul__(self: Tensor_S[Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...
    @overload
    def __mul__(self: Tensor_S[SomeDim], o: Number | Tensor_S[Dimless]) -> Tensor_S[SomeDim]: ...
    @overload
    def __mul__(self: Tensor_S[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_S[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __truediv__(self: Tensor_S[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def __truediv__(self: Tensor_S[Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_S[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: Tensor_S[SomeDim], o: Number | Tensor_S[Dimless]) -> Tensor_S[SomeDim]: ...
    @overload
    def __truediv__(self: Tensor_S[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_S[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __mod__(self: Tensor_S[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def __mod__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    @overload
    def __mod__(self: Tensor_S[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...
    def __mod__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __radd__(self: Tensor_S[Dimless], o: Number) -> Tensor_S[Dimless]: ...
    @overload
    def __radd__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rsub__(self: Tensor_S[Dimless], o: Number) -> Tensor_S[Dimless]: ...
    @overload
    def __rsub__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rmul__(self: Tensor_S[Dimless], o: Number) -> Tensor_S[Dimless]: ...
    @overload
    def __rmul__(self: Tensor_S[SomeDim], o: Number) -> Tensor_S[SomeDim]: ...
    def __rmul__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_S[Dimless], o: Number) -> Tensor_S[Dimless]: ...
    @overload
    def __rtruediv__(self: Tensor_S[SomeDim], o: Number) -> Tensor_S[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> Tensor_S[Any]: ...

    @overload
    def __rmod__(self: Tensor_S[Dimless], o: Number) -> Tensor_S[Dimless]: ...
    @overload
    def __rmod__(self: Tensor_S[SomeDim], o: Number) -> Never: ...
    def __rmod__(self, o: object) -> Tensor_S[Any]: ...


class Tensor_V3(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_components(
        cls,
        x: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
        y: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
        z: Tensor_S[SomeDim] | Number | npt.NDArray[np.float64],
    ) -> Tensor_V3[SomeDim]: ...

    @staticmethod
    def from_spherical(
        theta: Tensor_S[Angle],
        delta: Tensor_S[Angle],
        rho: Tensor_S[SomeOtherDim],
    ) -> Tensor_V3[SomeOtherDim]: ...

    @staticmethod
    def from_vectors(*vectors: Vector3[SomeDim]) -> Vector3Array[SomeDim]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    def copy(self) -> Tensor_V3[SomeDim]: ...

    @overload
    def dot(self: Tensor_V3[Dimless], o: Tensor_V3[Dimless]) -> Tensor_S[Dimless]: ...
    @overload
    def dot(self: Tensor_V3[Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_S[SomeOtherDim]: ...
    @overload
    def dot(self: Tensor_V3[SomeDim], o: Tensor_V3[Dimless]) -> Tensor_S[SomeDim]: ...
    def dot(self, o: Tensor_V3[SomeOtherDim]) -> Tensor_S[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Tensor_V3[Dimless], o: Tensor_V3[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def cross(self: Tensor_V3[Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    @overload
    def cross(self: Tensor_V3[SomeDim], o: Tensor_V3[Dimless]) -> Tensor_V3[SomeDim]: ...
    def cross(self, o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...

    @property
    def size(self) -> int: ...

    @property
    def x(self) -> Tensor_S[SomeDim]: ...

    @property
    def y(self) -> Tensor_S[SomeDim]: ...

    @property
    def z(self) -> Tensor_S[SomeDim]: ...

    @property
    def length(self) -> Tensor_S[SomeDim]: ...

    @property
    def length_squared(self) -> Tensor_S[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> Tensor_S[Angle]: ...

    @property
    def delta(self) -> Tensor_S[Angle]: ...

    def angle(self, o: Tensor_V3[SomeDim]) -> Tensor_S[Angle]: ...
    def normalized(self) -> Tensor_V3[Dimless]: ...
    def __getitem__(self, index: int) -> Vector3[SomeDim]: ...
    def __pos__(self) -> Tensor_V3[SomeDim]: ...
    def __neg__(self) -> Tensor_V3[SomeDim]: ...

    @overload
    def __add__(self: Tensor_V3[Dimless], o: Number | Tensor_V3[Dimless] | Tensor_S[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __add__(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeDim] | Tensor_S[SomeDim]) -> Tensor_V3[SomeDim]: ...
    def __add__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __radd__(self: Tensor_V3[Dimless], o: Number) -> Tensor_V3[Dimless]: ...
    @overload
    def __radd__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __sub__(self: Tensor_V3[Dimless], o: Number | Tensor_V3[Dimless] | Tensor_S[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __sub__(self: Tensor_V3[SomeDim], o: Tensor_V3[SomeDim] | Tensor_S[SomeDim]) -> Tensor_V3[SomeDim]: ...
    def __sub__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rsub__(self: Tensor_V3[Dimless], o: Number) -> Tensor_V3[Dimless]: ...
    @overload
    def __rsub__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __mul__(self: Tensor_V3[Dimless], o: Number | Tensor_S[Dimless] | Tensor_V3[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __mul__(self: Tensor_V3[Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    @overload
    def __mul__(self: Tensor_V3[SomeDim], o: Number | Tensor_S[Dimless] | Tensor_V3[Dimless]) -> Tensor_V3[SomeDim]: ...
    @overload
    def __mul__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rmul__(self: Tensor_V3[Dimless], o: Number) -> Tensor_V3[Dimless]: ...
    @overload
    def __rmul__(self: Tensor_V3[SomeDim], o: Number) -> Tensor_V3[SomeDim]: ...
    def __rmul__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __truediv__(self: Tensor_V3[Dimless], o: Number | Tensor_S[Dimless] | Tensor_V3[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __truediv__(self: Tensor_V3[Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: Tensor_V3[SomeDim], o: Number | Tensor_S[Dimless] | Tensor_V3[Dimless]) -> Tensor_V3[SomeDim]: ...
    @overload
    def __truediv__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Tensor_V3[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_V3[Dimless], o: Number) -> Tensor_V3[Dimless]: ...
    @overload
    def __rtruediv__(self: Tensor_V3[SomeDim], o: Number) -> Tensor_V3[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __mod__(self: Tensor_V3[Dimless], o: Number | Tensor_S[Dimless] | Tensor_V3[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __mod__(self: Tensor_V3[Dimless], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Never: ...
    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...
    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeDim] | Tensor_V3[SomeDim]) -> Tensor_V3[SomeDim]: ...
    @overload
    def __mod__(self: Tensor_V3[SomeDim], o: Tensor_S[SomeOtherDim] | Tensor_V3[SomeOtherDim]) -> Never: ...
    def __mod__(self, o: object) -> Tensor_V3[Any]: ...

    @overload
    def __rmod__(self: Tensor_V3[Dimless], o: Number) -> Tensor_V3[Dimless]: ...
    @overload
    def __rmod__(self: Tensor_V3[SomeDim], o: Number) -> Never: ...
    def __rmod__(self, o: object) -> Tensor_V3[Any]: ...


class Tensor_M33(Tensor[SomeDim], Generic[SomeDim]):
    def __init__(self, data: TensorData) -> None: ...

    @classmethod
    def from_elements(
        cls,
        a: Tensor_S[SomeDim] | Number,
        b: Tensor_S[SomeDim] | Number,
        c: Tensor_S[SomeDim] | Number,
        d: Tensor_S[SomeDim] | Number,
        e: Tensor_S[SomeDim] | Number,
        f: Tensor_S[SomeDim] | Number,
        g: Tensor_S[SomeDim] | Number,
        h: Tensor_S[SomeDim] | Number,
        i: Tensor_S[SomeDim] | Number,
    ) -> Tensor_M33[SomeDim]: ...

    @property
    def size(self) -> int: ...

    def cast(self, dim: type[SomeOtherDim]) -> Tensor_M33[SomeOtherDim]: ...
    def copy(self) -> Tensor_M33[SomeDim]: ...
    def __getitem__(self, index: int) -> Matrix33[SomeDim]: ...

    @overload
    def inverse(self: Tensor_M33[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def inverse(self: Tensor_M33[SomeDim]) -> Tensor_M33[QuotientDim[Dimless, SomeDim]]: ...
    def __pos__(self) -> Tensor_M33[SomeDim]: ...
    def __neg__(self) -> Tensor_M33[SomeDim]: ...

    @overload
    def __add__(self: Tensor_M33[Dimless], o: Tensor_M33[Dimless] | Tensor_S[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __add__(self: Tensor_M33[SomeDim], o: Tensor_M33[SomeDim] | Tensor_S[SomeDim]) -> Tensor_M33[SomeDim]: ...
    def __add__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __radd__(self: Tensor_M33[Dimless], o: Number) -> Tensor_M33[Dimless]: ...
    @overload
    def __radd__(self: Tensor_M33[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __sub__(self: Tensor_M33[Dimless], o: Tensor_M33[Dimless] | Tensor_S[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __sub__(self: Tensor_M33[SomeDim], o: Tensor_M33[SomeDim] | Tensor_S[SomeDim]) -> Tensor_M33[SomeDim]: ...
    def __sub__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rsub__(self: Tensor_M33[Dimless], o: Number) -> Tensor_M33[Dimless]: ...
    @overload
    def __rsub__(self: Tensor_M33[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __mul__(self: Tensor_M33[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __mul__(self: Tensor_M33[Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_M33[SomeOtherDim]: ...
    @overload
    def __mul__(self: Tensor_M33[SomeDim], o: Number | Tensor_S[Dimless]) -> Tensor_M33[SomeDim]: ...
    @overload
    def __mul__(self: Tensor_M33[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_M33[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rmul__(self: Tensor_M33[Dimless], o: Number) -> Tensor_M33[Dimless]: ...
    @overload
    def __rmul__(self: Tensor_M33[SomeDim], o: Number) -> Tensor_M33[SomeDim]: ...
    def __rmul__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __truediv__(self: Tensor_M33[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __truediv__(self: Tensor_M33[Dimless], o: Tensor_S[SomeOtherDim]) -> Tensor_M33[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: Tensor_M33[SomeDim], o: Number | Tensor_S[Dimless]) -> Tensor_M33[SomeDim]: ...
    @overload
    def __truediv__(self: Tensor_M33[SomeDim], o: Tensor_S[SomeOtherDim]) -> Tensor_M33[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __rtruediv__(self: Tensor_M33[Dimless], o: Number) -> Tensor_M33[Dimless]: ...
    @overload
    def __rtruediv__(self: Tensor_M33[SomeDim], o: Number) -> Tensor_M33[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __mod__(self: Tensor_M33[Dimless], o: Number | Tensor_S[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __mod__(self: Tensor_M33[Dimless], o: Tensor_S[SomeOtherDim]) -> Never: ...
    @overload
    def __mod__(self: Tensor_M33[SomeDim], o: Number) -> Never: ...
    @overload
    def __mod__(self: Tensor_M33[SomeDim], o: Tensor_S[SomeDim]) -> Tensor_M33[SomeDim]: ...
    @overload
    def __mod__(self: Tensor_M33[SomeDim], o: Tensor_S[SomeOtherDim]) -> Never: ...
    def __mod__(self, o: object) -> Tensor_M33[Any]: ...

    @overload
    def __matmul__(self: Tensor_M33[Dimless], o: Tensor_M33[Dimless]) -> Tensor_M33[Dimless]: ...
    @overload
    def __matmul__(self: Tensor_M33[Dimless], o: Tensor_M33[SomeOtherDim]) -> Tensor_M33[SomeOtherDim]: ...
    @overload
    def __matmul__(self: Tensor_M33[SomeDim], o: Tensor_M33[SomeOtherDim]) -> Tensor_M33[ProductDim[SomeDim, SomeOtherDim]]: ...
    @overload
    def __matmul__(self: Tensor_M33[Dimless], o: Tensor_V3[Dimless]) -> Tensor_V3[Dimless]: ...
    @overload
    def __matmul__(self: Tensor_M33[Dimless], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[SomeOtherDim]: ...
    @overload
    def __matmul__(self: Tensor_M33[SomeDim], o: Tensor_V3[Dimless]) -> Tensor_V3[SomeDim]: ...
    @overload
    def __matmul__(self: Tensor_M33[SomeDim], o: Tensor_V3[SomeOtherDim]) -> Tensor_V3[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __matmul__(self, o: object) -> Tensor[Any]: ...

    def __rmatmul__(self, o: object) -> Tensor[Any]: ...
    def __rmod__(self, o: object) -> Tensor_M33[Any]: ...


class Scalar(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, value: Number) -> None: ...

    @property
    def base_unit_value(self) -> Number: ...

    def magnitude(self, units: str = "1") -> Number: ...
    def cast(self, dim: type[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...
    def copy(self) -> Scalar[SomeDim]: ...
    def __pos__(self) -> Scalar[SomeDim]: ...
    def __neg__(self) -> Scalar[SomeDim]: ...

    @overload
    def __add__(self: Scalar[Dimless], o: Number | Scalar[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def __add__(self: Scalar[SomeDim], o: Number) -> Never: ...
    @overload
    def __add__(self: Scalar[SomeDim], o: Scalar[SomeDim]) -> Scalar[SomeDim]: ...
    @overload
    def __add__(self: Scalar[SomeDim], o: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
    def __add__(self, o: object) -> Scalar[Any] | ScalarArray[Any]: ...

    @overload
    def __sub__(self: Scalar[Dimless], o: Number | Scalar[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def __sub__(self: Scalar[SomeDim], o: Number) -> Never: ...
    @overload
    def __sub__(self: Scalar[SomeDim], o: Scalar[SomeDim]) -> Scalar[SomeDim]: ...
    @overload
    def __sub__(self: Scalar[SomeDim], o: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
    def __sub__(self, o: object) -> Scalar[Any] | ScalarArray[Any]: ...

    @overload
    def __mul__(self: Scalar[Dimless], o: Number | Scalar[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def __mul__(self: Scalar[Dimless], o: Scalar[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...
    @overload
    def __mul__(self: Scalar[SomeDim], o: Number | Scalar[Dimless]) -> Scalar[SomeDim]: ...
    @overload
    def __mul__(self: Scalar[SomeDim], o: Scalar[SomeOtherDim]) -> Scalar[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __truediv__(self: Scalar[Dimless], o: Number | Scalar[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def __truediv__(self: Scalar[Dimless], o: Scalar[SomeOtherDim]) -> Scalar[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: Scalar[SomeDim], o: Number | Scalar[Dimless]) -> Scalar[SomeDim]: ...
    @overload
    def __truediv__(self: Scalar[SomeDim], o: Scalar[SomeOtherDim]) -> Scalar[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __radd__(self: Scalar[Dimless], o: Number) -> Scalar[Dimless]: ...
    @overload
    def __radd__(self: Scalar[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rsub__(self: Scalar[Dimless], o: Number) -> Scalar[Dimless]: ...
    @overload
    def __rsub__(self: Scalar[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rmul__(self: Scalar[Dimless], o: Number) -> Scalar[Dimless]: ...
    @overload
    def __rmul__(self: Scalar[SomeDim], o: Number) -> Scalar[SomeDim]: ...
    def __rmul__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rtruediv__(self: Scalar[Dimless], o: Number) -> Scalar[Dimless]: ...
    @overload
    def __rtruediv__(self: Scalar[SomeDim], o: Number) -> Scalar[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __mod__(self: Scalar[Dimless], o: Number | Scalar[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def __mod__(self: Scalar[SomeDim], o: Scalar[SomeDim]) -> Scalar[SomeDim]: ...
    def __mod__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __rmod__(self: Scalar[Dimless], o: Number) -> Scalar[Dimless]: ...
    @overload
    def __rmod__(self: Scalar[SomeDim], o: Number) -> Never: ...
    def __rmod__(self, o: object) -> Scalar[Any]: ...

    @overload
    def __pow__(self: Scalar[Dimless], p: N4 | N3 | N2 | N1 | OO | P1 | P2 | P3 | P4) -> Scalar[Dimless]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: N4) -> Scalar[PowerDim[SomeDim, N4, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: N3) -> Scalar[PowerDim[SomeDim, N3, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: N2) -> Scalar[PowerDim[SomeDim, N2, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: N1) -> Scalar[PowerDim[SomeDim, N1, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: OO) -> Scalar[Dimless]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: P1) -> Scalar[PowerDim[SomeDim, P1, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: P2) -> Scalar[PowerDim[SomeDim, P2, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: P3) -> Scalar[PowerDim[SomeDim, P3, P1]]: ...
    @overload
    def __pow__(self: Scalar[SomeDim], p: P4) -> Scalar[PowerDim[SomeDim, P4, P1]]: ...
    def __pow__(self, p: Fraction | int | float) -> Scalar[Any]: ...


class ScalarArray(Tensor_S[SomeDim], Generic[SomeDim]):
    def __init__(self, values: npt.NDArray[np.float64]) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def base_unit_value(self) -> npt.NDArray[np.float64]: ...

    def magnitude(self, units: str = "1") -> npt.NDArray[np.float64]: ...
    def cast(self, dim: type[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...
    def copy(self) -> ScalarArray[SomeDim]: ...
    def __getitem__(self, index: int) -> Scalar[SomeDim]: ...
    def __pos__(self) -> ScalarArray[SomeDim]: ...
    def __neg__(self) -> ScalarArray[SomeDim]: ...

    @overload
    def __add__(self: ScalarArray[Dimless], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
    @overload
    def __add__(self: ScalarArray[SomeDim], o: Number) -> Never: ...
    @overload
    def __add__(self: ScalarArray[SomeDim], o: Scalar[SomeDim] | ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
    def __add__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __sub__(self: ScalarArray[Dimless], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
    @overload
    def __sub__(self: ScalarArray[SomeDim], o: Number) -> Never: ...
    @overload
    def __sub__(self: ScalarArray[SomeDim], o: Scalar[SomeDim] | ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
    def __sub__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __mul__(self: ScalarArray[Dimless], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
    @overload
    def __mul__(self: ScalarArray[Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...
    @overload
    def __mul__(self: ScalarArray[SomeDim], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[SomeDim]: ...
    @overload
    def __mul__(self: ScalarArray[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __truediv__(self: ScalarArray[Dimless], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
    @overload
    def __truediv__(self: ScalarArray[Dimless], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: ScalarArray[SomeDim], o: Number | Scalar[Dimless] | ScalarArray[Dimless]) -> ScalarArray[SomeDim]: ...
    @overload
    def __truediv__(self: ScalarArray[SomeDim], o: Scalar[SomeOtherDim] | ScalarArray[SomeOtherDim]) -> ScalarArray[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __radd__(self: ScalarArray[Dimless], o: Number) -> ScalarArray[Dimless]: ...
    @overload
    def __radd__(self: ScalarArray[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rsub__(self: ScalarArray[Dimless], o: Number) -> ScalarArray[Dimless]: ...
    @overload
    def __rsub__(self: ScalarArray[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rmul__(self: ScalarArray[Dimless], o: Number) -> ScalarArray[Dimless]: ...
    @overload
    def __rmul__(self: ScalarArray[SomeDim], o: Number) -> ScalarArray[SomeDim]: ...
    def __rmul__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rtruediv__(self: ScalarArray[Dimless], o: Number) -> ScalarArray[Dimless]: ...
    @overload
    def __rtruediv__(self: ScalarArray[SomeDim], o: Number) -> ScalarArray[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __rmod__(self: ScalarArray[Dimless], o: Number) -> ScalarArray[Dimless]: ...
    @overload
    def __rmod__(self: ScalarArray[SomeDim], o: Number) -> Never: ...
    def __rmod__(self, o: object) -> ScalarArray[Any]: ...

    @overload
    def __pow__(self: ScalarArray[Dimless], p: N4 | N3 | N2 | N1 | OO | P1 | P2 | P3 | P4) -> ScalarArray[Dimless]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: N4) -> ScalarArray[PowerDim[SomeDim, N4, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: N3) -> ScalarArray[PowerDim[SomeDim, N3, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: N2) -> ScalarArray[PowerDim[SomeDim, N2, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: N1) -> ScalarArray[PowerDim[SomeDim, N1, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: OO) -> ScalarArray[Dimless]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: P1) -> ScalarArray[PowerDim[SomeDim, P1, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: P2) -> ScalarArray[PowerDim[SomeDim, P2, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: P3) -> ScalarArray[PowerDim[SomeDim, P3, P1]]: ...
    @overload
    def __pow__(self: ScalarArray[SomeDim], p: P4) -> ScalarArray[PowerDim[SomeDim, P4, P1]]: ...
    def __pow__(self, p: Fraction | int | float) -> ScalarArray[Any]: ...


class Vector3(Tensor_V3[SomeDim], Generic[SomeDim]):
    O: ClassVar[Vector3[Dimless]]
    X: ClassVar[Vector3[Dimless]]
    Y: ClassVar[Vector3[Dimless]]
    Z: ClassVar[Vector3[Dimless]]

    @overload
    @classmethod
    def from_components(
        cls,
        x: Scalar[SomeDim],
        y: Scalar[SomeDim],
        z: Scalar[SomeDim],
    ) -> Vector3[SomeDim]: ...

    @overload
    @classmethod
    def from_components(
        cls,
        x: Number,
        y: Number,
        z: Number,
    ) -> Vector3[Dimless]: ...

    @staticmethod
    def from_spherical(
        theta: Scalar[Angle],
        delta: Scalar[Angle],
        rho: Scalar[SomeOtherDim],
    ) -> Vector3[SomeOtherDim]: ...

    @property
    def x(self) -> Scalar[SomeDim]: ...

    @property
    def y(self) -> Scalar[SomeDim]: ...

    @property
    def z(self) -> Scalar[SomeDim]: ...

    @property
    def length(self) -> Scalar[SomeDim]: ...

    @property
    def length_squared(self) -> Scalar[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> Scalar[Angle]: ...

    @property
    def delta(self) -> Scalar[Angle]: ...

    @overload
    def dot(self: Vector3[Dimless], o: Vector3[Dimless]) -> Scalar[Dimless]: ...
    @overload
    def dot(self: Vector3[Dimless], o: Vector3[SomeOtherDim]) -> Scalar[SomeOtherDim]: ...
    @overload
    def dot(self: Vector3[SomeDim], o: Vector3[Dimless]) -> Scalar[SomeDim]: ...
    def dot(self, o: Vector3[SomeOtherDim]) -> Scalar[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Vector3[Dimless], o: Vector3[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def cross(self: Vector3[Dimless], o: Vector3[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    @overload
    def cross(self: Vector3[SomeDim], o: Vector3[Dimless]) -> Vector3[SomeDim]: ...
    @overload
    def cross(self: Vector3[SomeDim], o: Vector3[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...
    def cross(self, o: Vector3[Any]) -> Vector3[Any]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    def copy(self) -> Vector3[SomeDim]: ...
    def angle(self, o: Vector3[SomeDim]) -> Scalar[Angle]: ...
    def normalized(self) -> Vector3[Dimless]: ...
    def __pos__(self) -> Vector3[SomeDim]: ...
    def __neg__(self) -> Vector3[SomeDim]: ...

    @overload
    def __add__(self: Vector3[Dimless], o: Number | Vector3[Dimless] | Scalar[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def __add__(self: Vector3[SomeDim], o: Vector3[SomeDim] | Scalar[SomeDim]) -> Vector3[SomeDim]: ...
    def __add__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __sub__(self: Vector3[Dimless], o: Number | Vector3[Dimless] | Scalar[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def __sub__(self: Vector3[SomeDim], o: Vector3[SomeDim] | Scalar[SomeDim]) -> Vector3[SomeDim]: ...
    def __sub__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __mul__(self: Vector3[Dimless], o: Number | Scalar[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def __mul__(self: Vector3[Dimless], o: Scalar[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    @overload
    def __mul__(self: Vector3[SomeDim], o: Number | Scalar[Dimless]) -> Vector3[SomeDim]: ...
    @overload
    def __mul__(self: Vector3[SomeDim], o: Scalar[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __mul__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __truediv__(self: Vector3[Dimless], o: Number | Scalar[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def __truediv__(self: Vector3[Dimless], o: Scalar[SomeOtherDim]) -> Vector3[QuotientDim[Dimless, SomeOtherDim]]: ...
    @overload
    def __truediv__(self: Vector3[SomeDim], o: Number | Scalar[Dimless]) -> Vector3[SomeDim]: ...
    @overload
    def __truediv__(self: Vector3[SomeDim], o: Scalar[SomeOtherDim]) -> Vector3[QuotientDim[SomeDim, SomeOtherDim]]: ...
    def __truediv__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __radd__(self: Vector3[Dimless], o: Number) -> Vector3[Dimless]: ...
    @overload
    def __radd__(self: Vector3[SomeDim], o: Number) -> Never: ...
    def __radd__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rsub__(self: Vector3[Dimless], o: Number) -> Vector3[Dimless]: ...
    @overload
    def __rsub__(self: Vector3[SomeDim], o: Number) -> Never: ...
    def __rsub__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rmul__(self: Vector3[Dimless], o: Number) -> Vector3[Dimless]: ...
    @overload
    def __rmul__(self: Vector3[SomeDim], o: Number) -> Vector3[SomeDim]: ...
    def __rmul__(self, o: object) -> Vector3[Any]: ...

    @overload
    def __rtruediv__(self: Vector3[Dimless], o: Number) -> Vector3[Dimless]: ...
    @overload
    def __rtruediv__(self: Vector3[SomeDim], o: Number) -> Vector3[QuotientDim[Dimless, SomeDim]]: ...
    def __rtruediv__(self, o: object) -> Vector3[Any]: ...


class Vector3Array(Tensor_V3[SomeDim], Generic[SomeDim]):
    @property
    def size(self) -> int: ...

    @property
    def x(self) -> ScalarArray[SomeDim]: ...

    @property
    def y(self) -> ScalarArray[SomeDim]: ...

    @property
    def z(self) -> ScalarArray[SomeDim]: ...

    @property
    def length(self) -> ScalarArray[SomeDim]: ...

    @property
    def length_squared(self) -> ScalarArray[PowerDim[SomeDim, P2, P1]]: ...

    @property
    def theta(self) -> ScalarArray[Angle]: ...

    @property
    def delta(self) -> ScalarArray[Angle]: ...

    @staticmethod
    def from_vectors(*vectors: Vector3[SomeDim]) -> Vector3Array[SomeDim]: ...

    @overload
    def dot(self: Vector3Array[Dimless], o: Vector3[Dimless]) -> ScalarArray[Dimless]: ...
    @overload
    def dot(self: Vector3Array[Dimless], o: Vector3[SomeOtherDim]) -> ScalarArray[SomeOtherDim]: ...
    @overload
    def dot(self: Vector3Array[SomeDim], o: Vector3[Dimless]) -> ScalarArray[SomeDim]: ...
    def dot(self, o: Vector3[SomeOtherDim]) -> ScalarArray[ProductDim[SomeDim, SomeOtherDim]]: ...

    @overload
    def cross(self: Vector3Array[Dimless], o: Vector3[Dimless]) -> Vector3Array[Dimless]: ...
    @overload
    def cross(self: Vector3Array[Dimless], o: Vector3[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...
    @overload
    def cross(self: Vector3Array[SomeDim], o: Vector3[Dimless]) -> Vector3Array[SomeDim]: ...
    def cross(self, o: Vector3[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...
    def copy(self) -> Vector3Array[SomeDim]: ...
    def angle(self, o: Vector3Array[SomeDim]) -> ScalarArray[Angle]: ...
    def normalized(self) -> Vector3Array[Dimless]: ...
    def __getitem__(self, index: int) -> Vector3[SomeDim]: ...
    def __pos__(self) -> Vector3Array[SomeDim]: ...
    def __neg__(self) -> Vector3Array[SomeDim]: ...


class Matrix33(Tensor_M33[SomeDim], Generic[SomeDim]):
    Id: ClassVar[Matrix33[Dimless]]

    @overload
    @classmethod
    def from_elements(
        cls,
        a: Scalar[SomeDim], b: Scalar[SomeDim], c: Scalar[SomeDim],
        d: Scalar[SomeDim], e: Scalar[SomeDim], f: Scalar[SomeDim],
        g: Scalar[SomeDim], h: Scalar[SomeDim], i: Scalar[SomeDim],
    ) -> Matrix33[SomeDim]: ...

    @overload
    @classmethod
    def from_elements(
        cls,
        a: Number, b: Number, c: Number,
        d: Number, e: Number, f: Number,
        g: Number, h: Number, i: Number,
    ) -> Matrix33[Dimless]: ...

    def cast(self, dim: type[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...
    def copy(self) -> Matrix33[SomeDim]: ...
    def __pos__(self) -> Matrix33[SomeDim]: ...
    def __neg__(self) -> Matrix33[SomeDim]: ...

    @overload
    def inverse(self: Matrix33[Dimless]) -> Matrix33[Dimless]: ...
    @overload
    def inverse(self: Matrix33[SomeDim]) -> Matrix33[QuotientDim[Dimless, SomeDim]]: ...

    @overload
    def __matmul__(self: Matrix33[Dimless], o: Matrix33[Dimless]) -> Matrix33[Dimless]: ...
    @overload
    def __matmul__(self: Matrix33[Dimless], o: Matrix33[SomeOtherDim]) -> Matrix33[SomeOtherDim]: ...
    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Matrix33[SomeOtherDim]) -> Matrix33[ProductDim[SomeDim, SomeOtherDim]]: ...
    @overload
    def __matmul__(self: Matrix33[Dimless], o: Vector3[Dimless]) -> Vector3[Dimless]: ...
    @overload
    def __matmul__(self: Matrix33[Dimless], o: Vector3[SomeOtherDim]) -> Vector3[SomeOtherDim]: ...
    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Vector3[SomeOtherDim]) -> Vector3[ProductDim[SomeDim, SomeOtherDim]]: ...
    @overload
    def __matmul__(self: Matrix33[Dimless], o: Vector3Array[Dimless]) -> Vector3Array[Dimless]: ...
    @overload
    def __matmul__(self: Matrix33[Dimless], o: Vector3Array[SomeOtherDim]) -> Vector3Array[SomeOtherDim]: ...
    @overload
    def __matmul__(self: Matrix33[SomeDim], o: Vector3Array[SomeOtherDim]) -> Vector3Array[ProductDim[SomeDim, SomeOtherDim]]: ...
    def __matmul__(self, o: object) -> Tensor[Any]: ...


class Matrix33Array(Tensor_M33[SomeDim], Generic[SomeDim]):
    @property
    def size(self) -> int: ...

    def cast(self, dim: type[SomeOtherDim]) -> Matrix33Array[SomeOtherDim]: ...
    def copy(self) -> Matrix33Array[SomeDim]: ...
    def __getitem__(self, index: int) -> Matrix33[SomeDim]: ...
    def __pos__(self) -> Matrix33Array[SomeDim]: ...
    def __neg__(self) -> Matrix33Array[SomeDim]: ...

    @overload
    def inverse(self: Matrix33Array[Dimless]) -> Matrix33Array[Dimless]: ...
    @overload
    def inverse(self: Matrix33Array[SomeDim]) -> Matrix33Array[QuotientDim[Dimless, SomeDim]]: ...


def ensure_tensor(o: Any | Tensor[SomeDim]) -> Tensor[SomeDim] | Tensor[Dimless]: ...
def ensure_same_dimensions(*tensors: Tensor[Any]) -> Literal[True]: ...


@overload
def abs(tensor: Scalar[SomeDim]) -> Scalar[SomeDim]: ...
@overload
def abs(tensor: ScalarArray[SomeDim]) -> ScalarArray[SomeDim]: ...
@overload
def abs(tensor: Vector3[SomeDim]) -> Vector3[SomeDim]: ...
@overload
def abs(tensor: Vector3Array[SomeDim]) -> Vector3Array[SomeDim]: ...
@overload
def abs(tensor: Matrix33[SomeDim]) -> Matrix33[SomeDim]: ...
@overload
def abs(tensor: Matrix33Array[SomeDim]) -> Matrix33Array[SomeDim]: ...
@overload
def abs(tensor: Tensor_S[SomeDim]) -> Tensor_S[SomeDim]: ...
@overload
def abs(tensor: Tensor_V3[SomeDim]) -> Tensor_V3[SomeDim]: ...
@overload
def abs(tensor: Tensor_M33[SomeDim]) -> Tensor_M33[SomeDim]: ...
def abs(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def square(tensor: Scalar[Dimless]) -> Scalar[Dimless]: ...
@overload
def square(tensor: ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
@overload
def square(tensor: Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
@overload
def square(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P2, P1]]: ...
@overload
def square(tensor: Scalar[PowerDim[SomeDim, P1, P2]]) -> Scalar[SomeDim]: ...
@overload
def square(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P2, P1]]: ...
@overload
def square(tensor: ScalarArray[PowerDim[SomeDim, P1, P2]]) -> ScalarArray[SomeDim]: ...
@overload
def square(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P2, P1]]: ...
@overload
def square(tensor: Tensor_S[PowerDim[SomeDim, P1, P2]]) -> Tensor_S[SomeDim]: ...
def square(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cube(tensor: Scalar[Dimless]) -> Scalar[Dimless]: ...
@overload
def cube(tensor: ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
@overload
def cube(tensor: Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
@overload
def cube(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P3, P1]]: ...
@overload
def cube(tensor: Scalar[PowerDim[SomeDim, P1, P3]]) -> Scalar[SomeDim]: ...
@overload
def cube(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P3, P1]]: ...
@overload
def cube(tensor: ScalarArray[PowerDim[SomeDim, P1, P3]]) -> ScalarArray[SomeDim]: ...
@overload
def cube(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P3, P1]]: ...
@overload
def cube(tensor: Tensor_S[PowerDim[SomeDim, P1, P3]]) -> Tensor_S[SomeDim]: ...
def cube(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def sqrt(tensor: Scalar[Dimless]) -> Scalar[Dimless]: ...
@overload
def sqrt(tensor: ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
@overload
def sqrt(tensor: Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
@overload
def sqrt(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P1, P2]]: ...
@overload
def sqrt(tensor: Scalar[PowerDim[SomeDim, P2, P1]]) -> Scalar[SomeDim]: ...
@overload
def sqrt(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P1, P2]]: ...
@overload
def sqrt(tensor: ScalarArray[PowerDim[SomeDim, P2, P1]]) -> ScalarArray[SomeDim]: ...
@overload
def sqrt(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P1, P2]]: ...
@overload
def sqrt(tensor: Tensor_S[PowerDim[SomeDim, P2, P1]]) -> Tensor_S[SomeDim]: ...
def sqrt(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cbrt(tensor: Scalar[Dimless]) -> Scalar[Dimless]: ...
@overload
def cbrt(tensor: ScalarArray[Dimless]) -> ScalarArray[Dimless]: ...
@overload
def cbrt(tensor: Tensor_S[Dimless]) -> Tensor_S[Dimless]: ...
@overload
def cbrt(tensor: Scalar[SomeDim]) -> Scalar[PowerDim[SomeDim, P1, P3]]: ...
@overload
def cbrt(tensor: Scalar[PowerDim[SomeDim, P3, P1]]) -> Scalar[SomeDim]: ...
@overload
def cbrt(tensor: ScalarArray[SomeDim]) -> ScalarArray[PowerDim[SomeDim, P1, P3]]: ...
@overload
def cbrt(tensor: ScalarArray[PowerDim[SomeDim, P3, P1]]) -> ScalarArray[SomeDim]: ...
@overload
def cbrt(tensor: Tensor_S[SomeDim]) -> Tensor_S[PowerDim[SomeDim, P1, P3]]: ...
@overload
def cbrt(tensor: Tensor_S[PowerDim[SomeDim, P3, P1]]) -> Tensor_S[SomeDim]: ...
def cbrt(tensor: Tensor[Any]) -> Tensor[Any]: ...


@overload
def cos(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def cos(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def cos(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def cos(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...


@overload
def sin(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def sin(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def sin(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def sin(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...


@overload
def tan(tensor: Scalar[Angle]) -> Scalar[Dimless]: ...
@overload
def tan(tensor: ScalarArray[Angle]) -> ScalarArray[Dimless]: ...
@overload
def tan(tensor: Tensor_S[Angle]) -> Tensor_S[Dimless]: ...
def tan(tensor: Tensor[Angle]) -> Tensor[Dimless]: ...


@overload
def acos(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def acos(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def acos(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def acos(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...


@overload
def asin(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def asin(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def asin(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def asin(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...


@overload
def atan(tensor: Scalar[Dimless]) -> Scalar[Angle]: ...
@overload
def atan(tensor: ScalarArray[Dimless]) -> ScalarArray[Angle]: ...
@overload
def atan(tensor: Tensor_S[Dimless]) -> Tensor_S[Angle]: ...
def atan(tensor: Tensor[Dimless]) -> Tensor[Angle]: ...


@overload
def atan2(y: Scalar[SomeDim], x: Scalar[SomeDim]) -> Scalar[Angle]: ...
@overload
def atan2(y: ScalarArray[SomeDim], x: ScalarArray[SomeDim]) -> ScalarArray[Angle]: ...
@overload
def atan2(y: Tensor_S[SomeDim], x: Tensor_S[SomeDim]) -> Tensor_S[Angle]: ...
def atan2(y: Tensor[SomeDim], x: Tensor[SomeDim]) -> Tensor[Angle]: ...


@overload
def normalize_angle(angle: Scalar[Angle]) -> Scalar[Angle]: ...
@overload
def normalize_angle(angle: ScalarArray[Angle]) -> ScalarArray[Angle]: ...
def normalize_angle(angle: Tensor[Angle]) -> Tensor[Angle]: ...


@overload
def normalize_angle_symmetric(angle: Scalar[Angle]) -> Scalar[Angle]: ...
@overload
def normalize_angle_symmetric(angle: ScalarArray[Angle]) -> ScalarArray[Angle]: ...
def normalize_angle_symmetric(angle: Tensor[Angle]) -> Tensor[Angle]: ...


@overload
def interpolate(t1: Scalar[SomeDim], t2: Scalar[SomeDim], alpha: Number) -> Scalar[SomeDim]: ...
@overload
def interpolate(t1: ScalarArray[SomeDim], t2: ScalarArray[SomeDim], alpha: Number) -> ScalarArray[SomeDim]: ...
@overload
def interpolate(t1: Vector3[SomeDim], t2: Vector3[SomeDim], alpha: Number) -> Vector3[SomeDim]: ...
@overload
def interpolate(t1: Vector3Array[SomeDim], t2: Vector3Array[SomeDim], alpha: Number) -> Vector3Array[SomeDim]: ...
@overload
def interpolate(t1: Matrix33[SomeDim], t2: Matrix33[SomeDim], alpha: Number) -> Matrix33[SomeDim]: ...
@overload
def interpolate(t1: Matrix33Array[SomeDim], t2: Matrix33Array[SomeDim], alpha: Number) -> Matrix33Array[SomeDim]: ...
@overload
def interpolate(t1: Tensor_S[SomeDim], t2: Tensor_S[SomeDim], alpha: Number) -> Tensor_S[SomeDim]: ...
@overload
def interpolate(t1: Tensor_V3[SomeDim], t2: Tensor_V3[SomeDim], alpha: Number) -> Tensor_V3[SomeDim]: ...
@overload
def interpolate(t1: Tensor_M33[SomeDim], t2: Tensor_M33[SomeDim], alpha: Number) -> Tensor_M33[SomeDim]: ...
def interpolate(t1: Tensor[SomeDim], t2: Tensor[SomeDim], alpha: Number) -> Tensor[SomeDim]: ...


class QuantityMeta(type):
    def __getattr__(cls, name: str) -> Scalar[Any]: ...


class Quantity(metaclass=QuantityMeta):
    @classmethod
    def get(cls, value: str) -> Scalar[Any]: ...

    dimensionless: Scalar[Dimless]

    radian: Scalar[Angle]
    turn: Scalar[Angle]
    degree: Scalar[Angle]

    meter: Scalar[Length]
    kilo_meter: Scalar[Length]
    radii_earth: Scalar[Length]
    radii_sun: Scalar[Length]
    astronomical_unit: Scalar[Length]

    second: Scalar[Time]
    minute: Scalar[Time]
    hour: Scalar[Time]
    day: Scalar[Time]
    month: Scalar[Time]
    year: Scalar[Time]

    kilo_gram: Scalar[Mass]
    gram: Scalar[Mass]
    metric_ton: Scalar[Mass]
